### ISSUE TITLE
Open-source development against binary files

### ISSUE THREAD

**Issue by tiagoboldt** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#1]
It is not trivial to contribute to this project while it is using binary pdf files. Specifically, there's no way to suggest changes to specific parts of the document and have them reviewed using pull requests. 

It would be great if this repository had the sources to build the document. Contributions could suggest changes by issuing pull requests. IAB could use those pull requests to ask for clarifications or merge the suggestions. 

Getting technical, an external process could keep the master branch sources compiled and available at all times, as the working version. Periodically, tagged releases could freeze the document into a new version, which could be made available through GitHub's repository download section and the web site. 

This is way more technical than what exists today, but if this project is to move forward in a truly open-source style, expecting contribution from the industry directly on GitHub, that's the way to go.

**Comment by mpatnode-si** [comment]
Hmm... it's almost like they didn't really want to see feedback...

**Comment by jenniferIAB** [comment]
First version PDF, and now we're really in action. Closing this comment thread - thanks for watching/participating!
