### ISSUE TITLE
Vendor list V2 is not publicly accessible

### ISSUE THREAD

**Issue by ashankz** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#100]
The file https://vendorlist.consensu.org/v2/vendor-list.json is not publicly accessible. It throws an error:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4FB06052A4B933D5</RequestId>
<HostId>
iNrGB+6llw+I+U4Fxz0z9+lkXfvBJHezPDiqw1LKXrmAkOWHAfNiDZyHQKlL+FF17z4B/R5nTZc=
</HostId>
</Error>

**Comment by chrispaterson** [comment]
Registration for the V2 Vendor List just started today.  It should be available soon.
