### ISSUE TITLE
Minor mistake in getInAppTCData example

### ISSUE THREAD

**Issue by etc-crontab** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#101]
On the page: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#getinapptcdata the example starts with:
`__tcfapi('getInTCData', 2, (inAppTCData, success) => {`
The name of the command to call seems incorrect; it should probably be:
`__tcfapi('getInAppTCData', 2, (inAppTCData, success) => {`

**Comment by chrispaterson** [comment]
Thanks @etc-crontab!
