### ISSUE TITLE
TCF-2 Example Strings.

### ISSUE THREAD

**Issue by TusherSUST** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#104]
The strings given as example in the TCF2 string format section do not conform to the provided rules.

The DisclosedVendor string is given as `PVAfDObdrA`. Which in binary becomes `00111101010100000001111100001100111001101101110110101100`.
From this I am getting:
- SegmentType: 1
- MaxVendorId: 60032
- IsRangeEncoding: 1
- NumEntries: 3852
      - IsARange: true

Then get exception since I can not read the next 16 bits for `StartOrOnlyVendorId`.

Am I missing something or are the examples invalid?

**Comment by chrispaterson** [comment]
These strings are in the spec for illustrative purposes only.

**Comment by chrispaterson** [comment]
Here's what should be a proper Disclosed Vendors string.

`IFZwEIADAALgAlgBeAGAANQAggBiAECAJkAYAA1wBwAEZAJhAV4BXwCzAFzANMAbgA34B9gECAIpARYAkuBMgEygJygUgBSICmQFSAKsgVcBV8CsgKz`
