### ISSUE TITLE
Enable CORS headers on vendorlist.json response

### ISSUE THREAD

**Issue by andresilveirah** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#109]
Hi there, 
I'm able to access the [vendorlist.json](https://vendorlist.consensu.org/vendorlist.json) via browser but not via `fetch`. It seems the response is missing the appropriate CORS headers.

```
Access to fetch at 'https://vendorlist.consensu.org/vendorlist.json' from origin 
'https://andresilveirah.github.io' has been blocked by CORS policy: No 
'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque
response serves your needs, set the request's mode to 'no-cors' to fetch the resource
with CORS disabled.
```

Any chance of adding the headers to the response?

**Comment by chrispaterson** [comment]
I think if you use a CURL request you'll see that the CORS header is set.  This seems to be an intermittent problem that I experience as well;  My Chrome browser gets stuck thinking there are no CORS headers being sent but if I inspect the request with CURL I can see the headers being sent.  Regardless, with V2 CMPs will be required to host their own vendor-list.json's.

**Comment by andresilveirah** [comment]
Thanks for the answer @chrispaterson  you're absolutely right. I've just tested with cURL and the response does include CORS headers
```
curl -H "Access-Control-Request-Method: GET" -H "Origin: http://localhost" --head https://vendorlist.consensu.org/vendorlist.json
```
```
HTTP/2 200
content-type: application/json; charset=utf-8
content-length: 94417
date: Sun, 15 Dec 2019 11:23:36 GMT
access-control-allow-origin: * <---------------------------
access-control-allow-methods: GET
access-control-max-age: 604800
last-modified: Thu, 12 Dec 2019 16:00:29 GMT
etag: "d4235702ad8b53f0cdf0070297b28726"
cache-control: max-age=604800
x-amz-version-id: 46J9XEoxi0yfpD4MttrQGqD7kPJU8xtn
accept-ranges: bytes
server: AmazonS3
vary: Accept-Encoding,Origin,Access-Control-Request-Headers,Access-Control-Request-Method
x-cache: Miss from cloudfront
via: 1.1 9810d82af8847b51b9c3048141069a65.cloudfront.net (CloudFront)
x-amz-cf-pop: FRA6-C1
x-amz-cf-id: kO9_gCtDtrSO6Z57giYPHSl5Pwz6fIza5BdFK5K1v-ZHa-s-cxvieg==
```

The funny thing is I just tried `fetch` again and it worked 🤷‍♂

**Comment by jcmartineztiempo** [comment]
Hi chrispaterson,

where do you have read that CMPs must host the GVL? Because I have the same error and I don't see anything in the official documentation?

Thanks
