### ISSUE TITLE
Which segments can be set for a global/specific TC string?

### ISSUE THREAD

**Issue by mlapeyre3** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#117]
Hi,

I was reading the specifications about the [TC string format](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md).

In [What are the different scopes for a TC String?](What are the different scopes for a TC String?) it is stated that:
* Global TC strings **must NOT contain Publisher restrictions or a Publisher TC segment** but they may contain a DisclosedVendors segment.
* Specific TC strings may contain Publisher restrictions, a Publisher TC segment and an AllowedVendors segment.

A few chapters below, in [TC String Format](TC String Format), there is different information:

> For example, a globally-scoped TC String with all four segments present would be surfaced through CMP API – not stored – and look like: [ Core String ].[ Disclosed Vendors ].[ AllowedVendors ].[ Publisher TC ]

I thought Global TC strings must NOT contain Publisher restrictions or a Publisher TC segment ...

And

> A service-specific TC String must contain a Core TC String and may optionally contain a Publisher TC segment, but **must not contain the OOB-related segments** because those segments are not allowed in service-specific contexts: [ Core String ].[ Publisher TC ]

I thought that Specific TC strings may contain Publisher restrictions, a Publisher TC segment **and an AllowedVendors segment**

What is true, what is false? 🤔 

Thanks!

**Comment by chrispaterson** [comment]
A Publisher TC is only allowed to be **STORED** in service specific contexts (ie. Publisher-specific values should not be stored in the globally shared context).  The CMP JavaScript API would append that segment on any calls to the api that return the TC string regardless of whether or not they are "service-specific" or "global" strings.  Likewise, if it is a "globally scoped" TC string you would never store the publisher-specific "allowedVendors" segment in the global cookie.

The first segment you quoted is talking about the storage and the second calls out the "not stored" distinction.

Does that make sense?

**Comment by mlapeyre3** [comment]
Hello @chrispaterson,

Thanks, that is pretty clear. I did not catch the distinction between what the CMP API would be able to return and what would be stored 👍

Thanks!

**Comment by tla-sirdata** [comment]
Hi @chrispaterson 

I'm dealing with the case of a TC String including a publisher TC segment in the global context.
I understand that the publisher TC segment can be surfaced through the CMP API but should not be stored globally.

My question is : how are we supposed to store the publisher TC segment then ?
Should we store a [Core string].[Publisher TC] TC String in a service-specific context ? Should we name it `eupubconsent-v2`?

Thanks
