### ISSUE TITLE
Translations for purposes not accessible

### ISSUE THREAD

**Issue by zvjerka24** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#120]
Per the documentation translations for purposes should be accessible through
https://vendorlist.consensu.org/v2/purposes-{language}.json
with list of supported languages
https://register.consensu.org/Translation

Once {language} is replaced with any of supported languages, it throws an error:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>
```

**Comment by saraneus** [comment]
Same here. This is quite urgent as we have to release our CMP end of this month.

**Comment by paooolino** [comment]
Same here.

**Comment by wittjill** [comment]
the v2 translations should be available this week.
