### ISSUE TITLE
Description of parameter incorrect

### ISSUE THREAD

**Issue by gnenadiclevi9** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#124]
In TCData object cmpStatus and eventStatus fields have contradictory description if we look at the documentation and usage. I believe that cmpStatus should refer to the [ping status codes](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#ping-status-codes) and eventStatus to the [addEventListener codes](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#addeventlistener) and not vice versa.

TCData = {
  tcString: 'base64url-encoded TC string with segments',
  tcfPolicyVersion: 2,
  cmpId:1000,
  cmpVersion: 1000,

  /**
   * true - GDPR Applies
   * false - GDPR Does not apply
   * undefined - unknown whether GDPR Applies
   * see the section: "What does the gdprApplies value mean?"
   */
  gdprApplies: Boolean,

  /*
   * **see addEventListener command**
   */
  cmpStatus: String,

  /**
   * **see Ping Status Codes in following table**
   */
  eventStatus: 'string', ...

**Comment by katiestroudpro** [comment]
Are we just saying with need to edit the last two reference notes in the excerpt provided?

/*
see addEventListener command
*/
eventStatus: 'string', ...

/*
see Ping Status Codes in the following table
*/
cmpStatus: String,

**Comment by gnenadiclevi9** [comment]
If this is the question for me I would say yes.

**Comment by katiestroudpro** [comment]
updated
