### ISSUE TITLE
New Validator still uses __cmp and not __tcfapi

### ISSUE THREAD

**Issue by saraneus** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#125]
The new validator wouldn't find any CMP API that is implementing TCF 2.0. Please update the validator to respect the new specification. See major changes: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#major-changes-from-11

**Comment by patrickverdon** [comment]
The new Validator only displays TCF v2 policy checks at the moment when you select 'Switch to TCF v2', technical checks will be added in due course.
