### ISSUE TITLE
Consent String V2 examples

### ISSUE THREAD

**Issue by SleimanJneidi** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#128]
Is it possible to have a valid Consent string for v2 in the specification, the one provided as a `Core String BObdrPUOevsguAfDqFENCNAAAAAmeAAA `
 seems to be a one taken from V1, the version in it is 1 and it is of length is 192 bits where publisherCC would reside at 197th bit.
Thanks.

**Comment by jamescooper-blis** [comment]
+1

**Comment by chrispaterson** [comment]
Hi, yes those are v1 strings.  When the specification was written v2 strings did not exist.  If you need a sample v2 string you can get one here http://www.iabtcf.com/#/encode
