### ISSUE TITLE
Does the Core segment need to begin with a SegmentType field?

### ISSUE THREAD

**Issue by jamescooper-blis** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#129]
The SegmentType enum assigns the value '0' to the Core segment, but this field is not the first field of the Core segment. Other segments have 'SegmentType' as the first field. Thus decoders cannot reliably tell, from the bits alone, if a segment is the Core segment.

The spec _does_ say that Core is required and comes first and so it can handled in that way, but it's pretty much a certainty that someone somewhere will send the segments out of order and it'd be nice if decoders could handle it.

- Remove any mention of Core from the SegmentType enum, or
- Prepend a SegmentType field to the Core segment

It's possible that someone sends two Core objects: the first identified as Core because it's first, and the second identified as Core because the SegmentType field is 0.

Edit: I suppose it's possible that the Core.Version field could be turned in to

Core.SegmentType : 3 bits   (0 -> Core)
Core.Version : 3 bits

since version 2 is encoded as '000010xx', but this would impose a limitation of 7 TCF versions.

**Comment by chrispaterson** [comment]
I think we can worry about that at version 7.
