### ISSUE TITLE
The example of the TC String is wrong

### ISSUE THREAD

**Issue by PauloMiranda98** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#131]
The TC String example of doc [Transparency and Consent String with Global Vendor List Format](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#tc-string-format) is wrong. This example is starting with 'B' and this is characteristic of v1.1

**Comment by DianeJane** [comment]
I also tried to decode the examples using iabtcfcli tool but the result is "Please pass a TC string".

**Comment by PauloMiranda98** [comment]
@DianeJane if you want to create a valid TCString V2, you can use this website: https://iabtcf.com/#/encode.

**Comment by DerekBoucher** [comment]
Does anyone know where exactly the checksum field is located in the string? The documentation does not specify it.

**Comment by carloslfu** [comment]
Thanks @PauloMiranda98!

**Comment by chrispaterson** [comment]
@DerekBoucher Checksum was removed before the string was final because it was unnecessary for determining encoding length (since each section defines that itself) and was creating problems for end padding.

**Comment by pm-harshad-mane** [comment]
in https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#tcdata in the "__tcfapiLocator" code example "__tcfapiLocator" is mentioned with extra "_", is it expected?

**Comment by alextcone** [comment]
> The TC String example of doc [Transparency and Consent String with Global Vendor List Format](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#tc-string-format) is wrong. This example is starting with 'B' and this is characteristic of v1.1

@PauloMiranda98, this issue is resolved with https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/commit/fb1a37c7be92bb3702913ead077320a4eeb1c83d
