### ISSUE TITLE
Consented purposes/ Special features in the tcData object returning as empty object rather having false value when consent is not given

### ISSUE THREAD

**Issue by sunandhaC** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#132]
According to the documentation: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#getinapptcdata
When consent is not given, tcData object should return false value but it returns empty object or sometimes consent for only few purposes based on the selection. So the response of the Api's is not consistent across all the conditions.

**Comment by chrispaterson** [comment]
@sunandhaC Is this in regards to the CMP API library?  If it is, can you file this on that GitHub repository?

**Comment by mghouseonetrust** [comment]
yes @chrispaterson
