### ISSUE TITLE
Url Macros with Custom Vendors

### ISSUE THREAD

**Issue by saraneus** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#134]
The spec says:

> 
> When a creative is rendered, it may contain a number of pixels under <img> tags. For example, <img src="http://vendor-a.com/key1=val1&key2=val2"> which fires an HTTP GET request from the browser to Vendor A’s domain.
> 
> Since the pixel is in an <img> tag without the ability to execute JavaScript, the CMP API cannot be used to obtain the TC String. All parties in the ad supply chain who transact using URLs must add a macro in their URLs where the TC String is inserted. Any caller with access to the applicable TC String must insert it within a URL containing the macro ${GDPR_CONSENT_XXXXX} where XXXXX is the numeric Vendor ID of the vendor receiving the TC string.
> 
> For example, for Vendor A with ID 123 to receive a TC String, an image URL must include a key-value pair with the URL parameter and macro gdpr_consent=${GDPR_CONSENT_123}.

What Id should we use when we are dealing with custom vendors who are not listed in the GVL like google?

**Comment by chrispaterson** [comment]
If the vendor is not on the vendor list, you cannot use the TCF
