### ISSUE TITLE
No 'Access-Control-Allow-Origin' header error while fetching vendor-list-v{version}.json or purposes-{language}.json

### ISSUE THREAD

**Issue by tla-sirdata** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#146]
https://vendorlist.consensu.org/v2/archives/vendor-list-v21.json
https://vendorlist.consensu.org/v2/purposes-fr.json

When fetching these TCF v2 files, the following error occurs : 
_Access to fetch at 'https://vendorlist.consensu.org/v2/archives/vendor-list-v21.json' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

It works well when fetching TCF v1 files : 
https://vendorlist.consensu.org/v-185/vendorlist.json
https://vendorlist.consensu.org/purposes-fr.json

**Comment by chrispaterson** [comment]
This is intended – You are required to host your own vendor-list.json.

**Comment by tla-sirdata** [comment]
So we are supposed to host all the vendor list versions ? We basically fetch `vendor-list-v{version}.json` when there is a particular version requested through the `getVendorList` command.

**Comment by chrispaterson** [comment]
Yes, that's right.  If you are a CMP you should host your own vendor-list.json archive.

**Comment by tla-sirdata** [comment]
OK thank you for the clarification, will do that.

**Comment by kirly-af** [comment]
Hi @chrispaterson,

On this: `You are required to host your own vendor-list.json`

Could you point to me where it is written in the spec?

This information might be missing (or at least I could not find it apart from here).

Thank you.
