### ISSUE TITLE
Translation of basic terms

### ISSUE THREAD

**Issue by TagCommander** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#149]
Hello !

I've read in the GUI guidelines that we have to indicate every purposes, special purposes etc... that each vendor is using.

But if we have translation for what each purposes means, we don't have translation for the terms : "Purpose", "Special Purpose", "Feature" etc...

Could you tell us if you plan to add some in the near future. Or why did you choose not to put those terms in the translation json ?

Thanks a lot !

**Comment by wittjill** [comment]
Hi, 
This was the same in v1. They are defined terms in the policy document, so we had them match, however, you may provide your own translation of basic terms if you wish.
