### ISSUE TITLE
The Base64 encoded consent-string example is wrong

### ISSUE THREAD

**Issue by thiru-startsmartlabs** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#15]
With the information presented in "Example Vendor Consent String", their Base64 encoded string should be BOEFEAyOEFEAyAHABDENAI4AAAB9vABAAJA not BOJObISOJObISAABAAENAA4AAAAAoAAA as given there.

**Comment by izhamoidsin** [comment]
It not the only one discrepancy. 
https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/16

**Comment by jenniferIAB** [comment]
PR #16 was merged. Closing this comment thread. Thank you!
