### ISSUE TITLE
Lack of examples for TCF v2 TCData and Consent String

### ISSUE THREAD

**Issue by kirly-af** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#152]
Hi,

It would be useful to have some examples of scenarios and the associated TCData/Consent-Strings. This would help a lot to have an idea of how to properly set the TCData and Consent-String.

There are three parts that I can not figure out:
* ~~legitimate interests~~
* publisher segment
* ~~flexible purposes~~

## Legitimate interests

~~The part I struggle the most the understand is the representation of the legitimate interests in the TCData/Consent-String.~~

~~Whereas the vendor-list vendors declare `legIntPurposes`, the Consent-String and TCData have two seperate sections: vendors.legitimateInterests and purposes.legitimateInterests.~~

~~I do not see a proper way to represent the legitimate interest establishment as there is no way to tell "I refuse the legitimate interest of purpose A for vendor B".~~

EDIT: webinar 2 explained a lot of things on this topic.

## Publisher segment

I do not see exactly what these parts represent:

* publisher.consents
* publisher.legitimateInterests
* publisher.customPurposes
* publisher.restrictions

My assumption is that publisher.consents and publisher.legitimateInterests are analog to the ones of each vendor. In that case, does it mean that the CMP should display a specific entry for the publisher the same way it handles vendors?

What are customPurposes meant to in that segment?

What is the point of restrictions? Is it only for flexible purposes? What should happen if a vendor declares a purpose as consent, and the publisher restricts it to legitimate interests for that vendor?
What about the opposite case (vendor declares legitimate interest, publisher restricts to consent)?

## Flexible purposes

~~It is not clear how these purposes should be handled. I guess the publisher as the possibility to use restrictions to make a decision on some of these. However, what should be the default behavior? (consent, legitimate interest?).~~

EDIT: I think I understood the default is set in either `purposes` or `legIntPurposes`

Thank you for your time

**Comment by wittjill** [comment]
Please review the policy document: https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/#7_Working_with_Publishers
Chapter IV: Policies for Publishers > 23. Managing Purposes and Legal Basis > 4 & 11 have relevant use cases.
