### ISSUE TITLE
Questions regarding 3rd Party Global Vendor Consent Cookie

### ISSUE THREAD

**Issue by potench** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#164]
## Background

I'm having a hard time understanding the technical implementation for a 3rd party global vendor consent cookie. Does the CMP _have_ to implement this or can we enforce 1st party cookie usage only? 

The following [documentation](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md#what-are-the-fields-of-the-global-vendor-consent-cookie-) suggests we should host some executable JS/HTML on the consensu.org domain:
> The DNS resolution for the name cmp-name.mgr.consensu.org will be delegated by the standardizing authority (IAB) to each CMP. CMPs will host their code, APIs, and CDN at this domain or subdomains.

 - How or who do we work with to map CNAMEs of ${cmp-name}.mgr.consensu.org to a company's CDN/hosting infrastructure? 
 - Is it a requirement to provide an implementation in the CMP to store consent globally?  Or can we enforce local consent only? Given many browsers do not allow 3rd party cookies by default, and more have publicly announced intentions to disable 3rd party cookies all together (Safari considers cookies set by an iframe to be 3rd party and blocks them), should we really even bother supporting this behavior in the CMP? 
 - Can we provide a local consent fallback if/when 3rd party cookies are disabled?
 - In general, there are browser limitations that impact a CMPs ability to store consent. Shouldn't the IAB be working with Browser vendors to implement a common UI, feature, and storage standard for consent management instead of asking JS developers to implement something that may not be operable? 

## More / Performance

I have a few other questions regarding performance of the CMP. Should I open a new issue to discuss web performance optimization around the CMP technical implementation? For example, the `globalVendorList` is now 90kb (and growing)... why do we need to load this file if it contains mostly unused information within the CMP?  The consent signal contains 2 properties that require synchronization: `globalVendorListVersion` and `maxVendorId`. Can CMP providers maintain a subset of the `globalVendorList` that contains both of these properties without packaging the entire global vendor list? 

It would be cool if IAB implemented a `<meta>` tag spec that allows publishers to declare their selected global and custom vendors, purposes, intents, and features. IAB could work with browser vendors or create browser extensions that can:
1. Interpret these tags to display the appropriate CMP UI 
2. Persist consent.
3. Provide a browser or JS API to the website to communicate consent choices.

**Comment by saraneus** [comment]
I'm sharing all your opinions and I don't understand why the IAB has not commented yet on them. Implementing a CMP is causing a lot of trouble with technical details such as 3rd party cookies and cross browser compatibility and also integration with different publisher sites.

We implemented a CMP which is using local cookies only and we are using a subset of the global vendor list, which can be administered by the publisher himself. It makes no sense to load the whole set (which is growing) if you only need one or two elements (stacks, vendors). Our CMP hasn't gone through the validator yet, so I can't be 100% sure by now whether this approach will be approved by the IAB.

**Comment by alextcone** [comment]
Hi @potench and @saraneus - sincere apologies that this has not been addressed. Have you been able to get anywhere reaching out directly to IAB Europe, which is managing TCF v2 CMP validation? If not, I am happy to connect you.

**Comment by asr-enid** [comment]
Hi @potench, can't give an official answer but some pointers

> Is it a requirement to provide an implementation in the CMP to store consent globally?

That is up to the publisher. You either work with 

- global scope -> needs to be saved within the global cookie
- service scope -> you can store the TC String as you like 

See here [Scope Definition](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#what-are-the-different-scopes-for-a-tc-string)

How service specific TC Strings are stored is completely up to you.

> Can we provide a local consent fallback if/when 3rd party cookies are disabled?

Yes, fallback is service specific scope. See link above
