### ISSUE TITLE
Features not present in Consent String

### ISSUE THREAD

**Issue by azhukovta** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#168]
Good day!
I've read the whole document and writing my consent string parser in Golang.
I found that there are such fields in Core String which correspond to vendors in https://vendorlist.consensu.org/v2/vendor-list.json:
- SpecialFeatureOptIns (=`specialFeatures` in vendor list)
- PurposesConsent (=`purposes` in vendor list)
- PurposesLITransparency (=`legIntPurposes ` in vendor list)
but I couldn't find how are the Features (`features` in vendor list) encoded?

**Comment by a3y** [comment]
As per this [link](https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/), the user is not given a choice to set "Feature" and "Special Purposes". Hence, those are not encoded in the TCString.
