### ISSUE TITLE
Typo in TCData object ?

### ISSUE THREAD

**Issue by tla-sirdata** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#170]
Hi,

In the TCData object specs (https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#tcdata), I think there's a typo in the `outOfBand` object : `discloseVendors` instead of `disclosedVendors`.

If so, can you correct it  ?

Thanks

**Comment by chrispaterson** [comment]
Good catch!  it should be `disclosedVendors`, I'll put in a fix.  Thanks!
