### ISSUE TITLE
Disclosed Vendors - Service specific scope

### ISSUE THREAD

**Issue by asr-enid** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#172]
The disclosed vendor segment would be highly valuable also in case of using it in conjunction with service specific TC Strings as it would provide the required metadata to correctly process the TC String directly within itself (self-contained, similar to publisher restrictions).

With the current specification the CMP needs to store the disclosed vendors as custom metatdata parallel to the TC String which might lead to faulty / errorness processing especially with headless CMPs, where this could be easily avoided by allowing disclosed vendors also with service scope.

From a technical processing perspective this should not pose any challenges given the scopes are completely separated in terms of how they are processed. Happy to do a PR no this.

**Comment by alextcone** [comment]
@chrispaterson do you remember if we ever discussed doing this?

**Comment by chrispaterson** [comment]
> as it would provide the required metadata to correctly process the TC String directly within itself (self-contained, similar to publisher restrictions).

I'm not following, what do you mean by "correctly process"?

> With the current specification the CMP needs to store the disclosed vendors as custom metatdata parallel to the TC String

In the global scope this is not true.  It's part of the string; just appended via a "."

> might lead to faulty / errorness processing especially with headless CMPs

I'm not sure what a "headless" CMP is.  To my knowledge this is not a viable thing because a user has to give "informed unambiguous consent.

**Comment by asr-enid** [comment]
> I'm not following, what do you mean by "correctly process"?
In terms of correctly displaying an existing status to a user (resurfacing the UI).  Just with the TC-String (service scope as defined in status quo) the CMP cannot differentiate between a consent that was not given for a vendor or a consent bit that is not set for a vendor, because the publisher chose to not disclose a vendor. Same general reasons why it is used with global scope, the assumption with service scope is that this information is stored using custom metadata to my understanding.

> In the global scope this is not true. It's part of the string; just appended via a "."
This issue only relates to service scoped TC Strings. As noted above to correctly resurface the TC String in the UI, the CMP needs to use custom metadata for the same information as defined in vendors disclosed. 

>I'm not sure what a "headless" CMP is. To my knowledge this is not a viable thing because a user has to give "informed unambiguous consent.
Headless meaning a pure JS-Script implementation of the CMP at a publisher, that keeps all config within browser storage (no persistent server backend). If the config ist lost for whatever reason (storage purge), the TC-String itself does not contain all the necessary information needed to distinguish "not set" from "never shown".

**Comment by chrispaterson** [comment]
I see.  Yes I've thought about this myself.  If you're using the @iabtcf/core library I've made it so that you can specify the segments you want to encode manually.  https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#encoding-options 

I think there's nothing preventing you from using it, but as far as making it part of the specification... That's a bigger process.

**Comment by asr-enid** [comment]
Ok - saw that, but was not sure it would cater for the situation. So one could encode a TC-String like that:
import {TCString, Segment} from '@iabtcf/core';
// 1. Prior to that create empty TC-Model (scope service), filter GVL to publishers vendor choice....
// 2. Show UI, establish legal basis
// 3. Encode default (no disclosed vendors)
const cmpApiEncodedString = TCString.encode(tcModel, { isForVendors: true });

const encodingOptions = {
  segments: [
    Segment.VENDORS_DISCLOSED
  ]
}
// 4. Encode disclosed vendors as per GVL filter
const customEncodedString = TCString.encode(tcModel, encodingOptions);`

**Comment by chrispaterson** [comment]
> When loading this "custom" service specific string would the be handled properly, that means would the GVL filters etc. be setup correctly?

It should handle all the filters of the GVL correctly.  If you narrow the GVL, those are the vendors set on the disclosed vendors segment regardless of if it's a service specific TC string or not.
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/TCString.ts#L59

**Comment by asr-enid** [comment]
@chrispaterson - Thanks, the Java implementation also seems to be generic here (when storing / loading), so this should be generally doable in service scope. When signalling you'd just ignore this segment, as during signalling service scoped string may not contain this segment as of now.
