### ISSUE TITLE
Purposes descriptions for publishers

### ISSUE THREAD

**Issue by tla-sirdata** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#175]
When a publisher enables purposes for its own, he can choose the standard purposes from the GVL.
In the UI the purposes are displayed separately from those for vendors.

The problem is that the legal descriptions in the GVL all refer to "vendors", we can't use them for publishers as it could lead to a misunderstanding for the user.
Examples : 
- purpose 1 : "Vendors can: store and access information..."
- purpose 3 : "To create a personalised ads profile vendors can..."

Is it possible to have in the GVL publisher-related descriptions for each purpose ?
Otherwise, is it allowed to use user-friendly descriptions for publishers ?

Thanks

**Comment by alextcone** [comment]
Hi @tla-sirdata, I'm following up with the policy working group at IAB Europe to find you an answer.

**Comment by tla-sirdata** [comment]
Hi @alextcone have you been able to find an answer ? Thanks
