### ISSUE TITLE
CMP Validator extension not found

### ISSUE THREAD

**Issue by saraneus** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#176]
The link to the Chrome extension does not work: https://cmp-validator.consensu.org/chrome-extension/latest/IAB-Europe-CMP-Validator-User-Guide.pdf

Please provide a working link!

**Comment by saraneus** [comment]
Never mind, I logged in with the wrong account, so Chrome gave me a 404

**Comment by alextcone** [comment]
Hi @saraneus, sorry to leave you hanging on this. I'm glad you were able to resolve!
