### ISSUE TITLE
Interpretation of missing keys on mobile storage

### ISSUE THREAD

**Issue by Amokrane** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#179]
Hello,

I have a question regarding an edge case I was thinking about. On mobile, vendors read directly from SharedPreferences or NSUserDefaults the relevant values stored under the specified keys (IABTCF_gdprApplies, IABTCF_IABTCF_TCString, IABTCF_VendorConsents).

One aspect missing from the spec is the fact that writing values to these different keys is not an atomic operation. Therefore, we can probably encounter a situation in the field where one or two values are missing.

What should be the most sensible action to take from a vendor perspective in this case? My hunch is that it is either the responsibility of the CMP or publisher to ensure that the relevant values are all properly stored and that vendors can outright ignore them if it's not the case.

I am curious to know your thoughts on this.

Thank you.

**Comment by alextcone** [comment]
Hi @Amokrane, I posed this question to several Tech Lab and IAB Europe members using the Tech Lab's privacy slack. I'll report back when I get consensus.
