### ISSUE TITLE
Specify which direction BitField is to be read

### ISSUE THREAD

**Issue by GwangGwang** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#18]
BitField lacks description as to how it should be understood: 

**1. Which direction should it be read?**
At least for this point for now I assume it to be interpreted the same manner as PurposesAllowed:

> Purpose #1 maps to the first (most significant) bit, purpose #24 maps to the last (least significant) bit.

As in, the leftmost bit maps to vendor 1, ... rightmost bit maps to vendor MaxVendorId

**2. How do the vendors get mapped to the bit index?**
Which of the two following scenarios is the correct way to interpret the bit indices?

1) Bit index maps to vendor Id
First bit maps to vendor with vendor id = 1, second bit to id = 2, etc.

2) Bit index maps to the index within the list of vendors
https://vendorlist.consensu.org/vendorlist.json
First (i.e. index 0 bit) refers to the index 0 vendor in the above vendorlist, in which case, "Emerge Sverige AB".

**Comment by jamesacooper** [comment]
"Emerge Sveriga AB" has id 8, not 0.

**Comment by jamesacooper** [comment]
I don't think the position in the vendorlist array matters, it doesn't seem to be sorted in any way.
What matters is the 'id' field of each object in the json array; it would make most send to use this to map to the appropriate bit in the bitfield.
