### ISSUE TITLE
Postpone implementation deadline due to Corona Virus

### ISSUE THREAD

**Issue by saraneus** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#180]
Would it make sense to postpone the deadline for implementing the CMP by a few months? The whole world is fighting the virus and a lot of  companies are not working due to protect their employees, probably including the IAB. There are unanswered issues which have been posted many days ago.

We appreciate any feedback!

**Comment by alextcone** [comment]
This is currently being discussed within IAB Europe. There is not yet a decision, however I can update this thread once a decision is taken.

**Comment by lon-pilot-mpf** [comment]
@alextcone we should close this since the deadline was extended (twice).
