### ISSUE TITLE
Service specific vendor list version not accepted by validator

### ISSUE THREAD

**Issue by saraneus** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#182]
We created a service specific CMP based on TCFv2 and the official Validator shows two tests failing:
![image](https://user-images.githubusercontent.com/39457035/77879189-698c1f00-728c-11ea-97c7-475d38abbc2c.png)
Our CMP uses a proprietary vendor list version because the publisher can update the vendor list any time by adding/removing vendors and deploy a new version, so that the CMP recognises the new version and displays the UI again. We use the property "vendorListVersion" for this purpose.

Does this approach violate the TCF and how can we satisfy the Validator?

**Comment by saraneus** [comment]
@alextcone Thanks for your reply. I would like to clarify that we use a subset of the vendors of the IAB Europe hosted Vendor list with all the official names and translations. This subset can be managed by the publisher himself. He can also add custom vendors which are presented in the same UI but separately from the IAB vendors. I have seen this approach in a UI Mockup created by the IAB.

So basically we are using the content of the official GVL but use a different technical approach to deliver that content to our CMP to optimise delay created by network traffic. Can you please explain where exactly does this violate the legal basis? I didn"t find anything about that in the TCF.

**Comment by patrickverdon** [comment]
The policies mandate that the latest version of the GVL is used whenever the CMP UI is shown. The only way of determining this is by checking the vendorListVersion. The fact that your custom GVL has a different version is therefore causing the technical check in the Validator to fail. 

I would recommend against customising the GVL, as the optimisation of only including vendors used by the publisher will not amount to much, given that the GVL is gzipped over the wire. 

If you intend to continue with this approach, you need to ensure that the vendorListVersion is the same as the current GVL version for the sub-set being used, in order for the test to pass. You will need to use a different property for the CMP to check before displaying the UI again.

Note that non-TCF vendors cannot be stored with dummy vendor ids in the GVL.

**Comment by saraneus** [comment]
The TC String doesnt allow to store a custom version property. There should be an option for that because I think it is a reasonable feature to - as a publisher - be able to add/remove vendors in the CMP as needed and capture consent immediately after any change. Publishers usually only work with a subset of those vendors in the GVL and will add/remove entries as they acquire/unacquire vendors on their websites. Any change to the publisher's own vendor list is the true version of the vendor list which should be stored in the service specific cookie.

Can we discuss to add a custom version property in the TCModel?

FYI: We added custom vendors (as an extra property) and meta information to the GVL to satisfy the needs of our CMP. It makes no sense in my opinion to separate the lists and create two requests for what can be done in one. The consent for the custom vendors is stored in a separate cookie, though.

**Comment by patrickverdon** [comment]
Publishers can use a sub-set of vendors without needing to have a custom version of the GVL. The CMP can track changes to the white list of vendors and act as they see fit. The version of the GVL in the TC String must refer to an actual version of the GVL, as vendors must load the version of the GVL used when the user gave consent, to determine what their legal basis was at that given time for data processing purposes, as well as for partners downstream who they pass data to. This would not be possible if everyone used their own proprietary GVL version.

And as far as network optimisations are concerned, the GVL as it stands gzipped is only 12K over the wire, so the benefit may not warrant the effort.

**Comment by chrispaterson** [comment]
The ability to narrow the `GVL` vendors is documented on the core library readme https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#narrow-the-list-of-vendors

**Comment by saraneus** [comment]
Thanks a lot for your time to discuss this. I think my point isn't clear yet or I missed something.

The point is that a white list concept needs a version number so that the CMP knows when the white list itself has changed. For example, when the publisher added a new vendor to the list, the CMP should popup to capture consent for this additional vendor. That mechanism is independent from the GVL version. To know whether the white list changed the CMP needs to store a white list version number with the cookie. If the TC String doesn't allow to do so we will need so store another cookie to achieve that goal.

How is the white list used? I only know about the _narrowVendorsTo_ function. There seems to be no function for narrowing Stacks.

About optimisations: I think the TCF should leave technical optimisations to the CMPs as their implementation requirements might be different from another as long as the legal basis is satisfied. It is not only about request size, it is also about decreasing the number of requests a CMP has to make on each page visit. In case of using a white list we will have to add one additional request.

**Comment by patrickverdon** [comment]
Yes you're right, there is no provision in the TC String to manage a white list of vendors and any changes to it. This behaviour is outside the scope of the tech specs and is up to the CMP to implement and yes, the data would need to be persisted somewhere other than the TC String.

**Comment by asr-enid** [comment]
@saraneus - see here: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/issues/172

This discussion addresses your question I assume, it a good way to deal with it, though not part of the tech specs (yet ;))
