### ISSUE TITLE
Validator throwing errors

### ISSUE THREAD

**Issue by saraneus** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#183]
The CMP Validator is throwing several errors:
![image](https://user-images.githubusercontent.com/39457035/77879917-0bf8d200-728e-11ea-9a24-71c92dfb5e02.png)

Reproduce:
I just installed the extension, then started Chrome in Incognito mode and surfed on the website where the CMP is installed. The UI popped up and I ran the Validator.

Browser: Chrome Version 79.0.3945.88 (Official Build) (64-bit)
OS: Ubuntu 18.04

**Comment by alextcone** [comment]
@patrickverdon are you able to provide guidance here?

**Comment by patrickverdon** [comment]
It looks like it's just trying to call the optional 'getVendorList' API command which doesn't appear to be implemented but it's difficult to know without running the Validator on the site itself. It looks like you're running on localhost though - if you have a dev site I can try let me know. Thanks.

**Comment by dmdabbs** [comment]
Cleaning house!

David
