### ISSUE TITLE
IAB TCF 2.0 Javascript support

### ISSUE THREAD

**Issue by zedwill** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#184]
Currently, there seems not to be an official SDK for the changes on the consent string introduced in TCF 2.0, with the notable exception of the Java language.

The JS SDK, in particular, states it is only compatible with v1.1. Here: https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-JS

Is there a timeline for 2.0 support on the official SDKs? Can you recommend a Go Lang SDK that supports v2.0?

**Comment by alextcone** [comment]
@zedwill - right now the only two libraries with active development are the Java and Javascript libraries. We've had requests for Swift and Go. Regarding requests, IAB Tech Lab is a member supported not for profit whose specifications and software development are almost fully member driven. This means we need volunteers to dedicate time and expertise to SDK / library creation. If you or your company is interested in contributing, please let me know. My email is alex.cone@iabtechlab.com.

**Comment by chrispaterson** [comment]
The JavaScript TCF v2.0 compatible version is here https://github.com/interactiveAdvertisingBureau/iabtcf-es

**Comment by zedwill** [comment]
@alextcone understood, we have no plans of implementing the library in Go ourselves, but I will check internally and if the situation changes I will contact you

**Comment by zedwill** [comment]
@chrispaterson Thanks! that is what we needed. 

Please feel free to close the issue

**Comment by tla-sirdata** [comment]
@zedwill As you were looking for a Go support, I just want to let you know that we developed a Go library to encode/decode TCF v2.0 TC Strings : https://github.com/SirDataFR/iabtcfv2

Let me know what you think about it and feel free to open issues if needed.
I hope it will help.
