### ISSUE TITLE
CMP's must now host their own copy of the global vendor list

### ISSUE THREAD

**Issue by a2intl** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#187]
There is now a requirement that CMP’s serve the vendorlist from their own content server (since the CORS headers aren’t being output on the v2 vendorlist URL, which makes it impossible to fetch via XmlHttpRequest). However, the vendorlist spec, implementation guidelines, and policies don’t mention this (apparently new) requirement. In fact, the vendorlist spec goes into depth about how the cache headers must be respected, which doesn't seem applicable now, at least not from a user's browser point-of-view. The vendorlist spec, CMP implementation guidelines, and policy (if necessary) should be updated with this new requirement. There's also a new requirement (that needs to be specified) of how soon after a new version of the GVL is published that CMP's are required to check for, update their version, and start using it.

**Comment by alextcone** [comment]
Note this is now being discussed on #193 (please add any feedback there)
