### ISSUE TITLE
https://my-cmp.mgr.consensu.org/cmp.js URL not working

### ISSUE THREAD

**Issue by AlbiTaga** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#188]
Hi All,

In the sample CMP code there is the following code that seems is not working properly. I would like to ask to you if the URL that follows is just a sample (and so it does not work for this reason) or actually it does not work because the URL is corrupted: https://my-cmp.mgr.consensu.org/cmp.js

Please, let me know.
Kind regards,
Albi

**Comment by alextcone** [comment]
It is a sample.

**Comment by AlbiTaga** [comment]
Hi Alex,

Thank you for your prompt reply. I would like to ask to you if it is mandatory to replace it with any other URL in order to make everything work properly or It can be removed without particular problems.
If I have to replace it, please, could you explain to me which URL should be inserted in?

Many thanks,
Albi
