### ISSUE TITLE
EndVendorId fields need some clarifications

### ISSUE THREAD

**Issue by geelweb** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#189]
Hi,

I'm working on a parser to decode the TCString and reading [this spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md)  I have a question about the EndVendorId fields.

The field is in the "Vendor Consent", "Vendor Legitimate Interest" and "Publisher Restrictions" sections of the Core String. The field is also in the Disclosed Vendors and Allowed Vendors segments.

The field description is the same in all cases :

> The last ID of the inclusive contiguous ascending-order series of Vendor IDs started with StartOrOnlyVendorId but only if that series has a cardinality greater than 1, otherwise this field is omitted. 

What I understand is than this field can be omitted if `isARange=1` and `StartOrOnlyVendorId=MaxVendorId-1`, because in this case the only possible value for EndVendorId is MaxVendorId. But this is not possible for the "Publisher Restriction" section...

So if we can have some things like

```
# 000000000011 0 0000000000000010 1 0000000000000100 1 0000000000000111 0000000000001100
{
  NumEntries: 3
  RangeEntry: [
    [
      IsARange: 0,
      StartOrOnlyVendorId: 2
    ],
    [
      IsARange: 1,
      StartOrOnlyVendorId: 4
    ],
    [
      IsARange: 1,
      StartOrOnlyVendorId: 7
      EndVendorId: 12
    ],
  ]
}
```
How can I know when I parse a range if I have to read the first bit of the next range or the last 16 bits of the current range ?

Can you give me some clarifications on how this field works ?

Regards,
Guillaume

**Comment by jamescooper-blis** [comment]
You only need to read EndVendorId if IsARange is 1.
The value of MaxVendorId does not control any part of the parsing logic. It's only used when querying the decoded string later.
The logic is something like:

```
isARange = readNext1(daisybit);
endId = startId = readNext16(daisybit);
if (isARange == 1) {
    endId = readNext16(daisybit);
}
```

**Comment by geelweb** [comment]
It's what I did, but the field description installed the doubt...
