### ISSUE TITLE
Macro replacement confusion

### ISSUE THREAD

**Issue by denisorlov84** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#196]
At [documentation ](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#how-does-a-url-based-service-process-the-tc-string-when-it-cant-execute-javascript) level it is an example how ${GDPR_CONSENT_XXXXX} macro should be replaced:

URL is:
`http://vendor-a.com/key1=val1&key2=val2&gdpr_consent=${GDPR_CONSENT_123}`

If the TC String is: `COvFyGBOvFyGBAbAAAENAPCAAOAAAAAAAAAAAEEUACCKAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw`

Replacement result is:
`http://vendor-a.com/key1=val1&key2=val2&gdpr_consent=BOPnWgIOPnWgIAAABAENAI4AAAAA0ABA`

Looks like that we should pass just part of consent related to vendor 123, but there is no description how to get this part from the initial consent String. Also, if we are trying to parse out data from 
`BOPnWgIOPnWgIAAABAENAI4AAAAA0ABA` it does not make any sense.

**Comment by alextcone** [comment]
Hi @denisorlov84. Thanks for flagging that mistake I resolved it with 7ab1025
