### ISSUE TITLE
advertisingconsent.eu is down

### ISSUE THREAD

**Issue by nioann** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#197]
Thanks for all the work in this repository.

Unfortunately advertisingconsent.eu has been down for 2-3 now, which makes it difficult to use it.

**Comment by jawadst** [comment]
@nioann I think the domain was deprecated a few months ago and everything is on https://iabeurope.eu/tcf-2-0/ and in this repository now. Were you looking for something in particular on that website? All of its content is on the IAB Europe website.
