### ISSUE TITLE
Consent String SDK links are invalid

### ISSUE THREAD

**Issue by eyedar** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#20]
The links to the JavaScript and C Consent String SDKs from GDPR-Transparency-and-Consent-Framework/Consent String SDK/Transparency and Consent Framework Consent String SDK Resources.md lead to invalid pages.

The JavaScript link leads to https://raw.githubusercontent.com/InteractiveAdvertisingBureau/Consent-String-SDK-JS which says "404: Invalid request."

The C link lead to https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-C and that brings up a GitHub 404 page.

**Comment by chrispaterson** [comment]
Thanks!  I fixed it
