### ISSUE TITLE
Leveraging the __cmp API to determine whether personalized ad content may be shown

### ISSUE THREAD

**Issue by thijsl** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#203]
Hi all,

_I think my question is as 101 as it gets. That being said, to my surprise, I couldn't find a clear answer or code example on the internet, so this thread might help out some newbies like myself._

How can client-side developers leverage the `__cmp` API to determine whether personalized ad content may be shown, specifically related to video advertising and the query parameters in an ad tag? (What are some code examples?)

**_Why?_**
When configuring (video) ad tags, one of the ad tag parameters may relate to GDPR and user consent.

Examples:
* [Google Ad Manager](https://developers.google.com/interactive-media-ads/docs/sdks/html5/consent) 
   * Add `&npa=1` to your ad tag to specify that only non-personalized ad content should be returned.
* [SpotX](https://developer.spotxchange.com/content/local/docs/publisher-resources/Supported-Parameters.md)
   * Add `regs[gdpr]=1` to your ad tag to specify that GDPR applies to the user.
   * Use `user[consent]` in your ad tag to specify the type of consent of the user.

Thus, on the client-side, you might want to implement some JavaScript which leverages the  `__cmp` API to determine the values of specific query parameters in the ad tag.

**_How?_**
In this advertising use-case, there are typically two things you are interested in on the client-side: 
1. Checking if GDPR applies;
2. Checking if the user allows personalized ads / has consented to information sharing.

_1. Checking if GDPR applies_
I think `#1` is pretty straightforward, and can be detected with the snippet below:
```
__cmp('getVendorConsents', null, function(data) {
    console.log(data);
    console.log("GDPR applies:", data.gdprApplies);
})
```
It would be great if someone could confirm this though.

_2. Checking if the user allows personalized ads_
I haven't completely figured out how to do `#2` yet -- how to programmatically decide whether personalized ads may (not) be shown (/whether the user has consented to information sharing). *How do you do this? What is a code example to detect whether personalized ads are allowed?* 

Are one of the following 3 approaches (almost) correct?

2.1. Is it as simple as checking the 5 basic purpose consents in the snippet below?
```
__cmp('getVendorConsents', console.log, function(data) {
    console.log(data);
    console.log(data.purposeConsents);
})
```
Then, you look up the different keys of `data.purposeConsents` in the following [table](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md#what-are-the-purposes-and-features-being-supported-)/dictionary:
|  Purpose ID |  Purpose |
|---|---|
|  1  | Information storage and access  |
|  2 |  Personalisation |
|  3 |  Ad selection, delivery, reporting |
|  4 |  Content selection, delivery, reporting |
|  5 |  Measurement |

In the case of allowing personalized video ads, you can use the following to check whether it is allowed:
```
var personalizedVideoAdsAllowed = data.purposeConsents[2];
```
Is this approach correct? If so: when would the other 4 purposes be relevant?

Additionally, if this would be correct, what in the case of [CMP API v2](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#tcdata), where `getVendorConsents` is no longer a supported command? Is the snippet below (almost) correct for v2?
```
__tcfapi('getTCData', 2, (tcData, success) => {
  if(success) {
    var personalizedAdsAllowed = tcData.purpose.consents[2];
  }
});
```

2.2. I feel like it is related to knowing which vendor the ad tag relates to. Then, you must be able to associate the vendor with a vendor ID, and look up the list of purpose IDs for that vendor ID. Then, for each purpose ID, you must know what that purpose stands for. One of those purposes stands for (allowing) personalized video ads. 
This approach seems overly complex, because as a client-side developer, you must then maintain dictionaries of vendors and purposes, and also determine the vendor ID from the ad tag (domain). (And what if the ad tag domain is a proxy? Or what if you're doing server-side ad-insertion?)

2.3. Alternatively, it might be related to the `consentData` returned by `__cmp('getConsentData', null, console.log)`, and then decoding this. That being said, when I run such a string through, https://iabtcf.com/#/decode, it returns a series of bits -- not too user friendly.

**_Moving forward_**
I'm going to continue to read through the specification, and try out some things, but it would be great if anyone could provide some insights and code snippets which would tackle these real-life SpotX and Google Ad Manager cases.

Thanks for reading. ☺

**Comment by alextcone** [comment]
It appears you're building to v1.1. That is not advisable. This issue is answered in v2 and v1.1 is to be deprecated August 15, 2020. Also, Google is supporting v2 so you do not need to do a translation of Google's "Personalized Advertising" into TCF terms. They have docs for this: https://support.google.com/admanager/answer/9461778?hl=en

**Comment by thijsl** [comment]
Hi @alextcone, thanks for the response! I didn't know about this article on Google's side. (I also touched v2 in "2.1".)

It indeed seems like Google will support something _in the future_, but this article does not necessarily answer the core of my question. (Or am I mistaken? If so: could you please elaborate?)

So to get back to my question: How would you leverage the __cmp API v2 to determine whether personalized ad content may be shown (e.g. for SpotX, Google, ... ad tag query parameters).

**Comment by lon-pilot-mpf** [comment]
Hi @thijsl In your original post I think your idea of 2.2 is kind of close. Under TCF V2, there is a macro facility for Tag-based services which may work here. This consists of two macros: ${GDPR} and ${GDPR_CONSENT_XXX} the vendor would need to include both of those in their tag. The main thing here is the XXX in the macro is the vendor id so you can look up their consent information in the TCstring.
