### ISSUE TITLE
Public access to the global vendor list in json format

### ISSUE THREAD

**Issue by Doca** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#211]
Is there a way to access the global vendor list without being registered as a CMP?

**Comment by lon-pilot-mpf** [comment]
There is no requirement to authenticate to get access to the GVL. Do note that there are restrictions on how often you can request it, but other than that it's freely available here: https://vendorlist.consensu.org/v2/vendor-list.json
