### ISSUE TITLE
Documentation for purposes' legitimate interests in "cmpuishown" event status

### ISSUE THREAD

**Issue by kemalmustafic** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#227]
The [documentation](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#addeventlistener) for the `addEventListener` command (table with `eventStatus`) specifies that `cmpuishown` event should contain a consent string with all vendors' consents set to `false` and all vendors' legitimate interest statuses set to `true`, but does not specify anything for the purposes' legitimate interest statuses. 

The legitimate interest status for all displayed purposes should be set to true in the consent string for this event status.

Could you please update the documentation for it so it includes the explanation for the purposes' legitimate interests?

**Comment by HeinzBaumann** [comment]
@kemalmustafic This has been entered against the old 2.1 spec. The spec has been updated and this paragraph has been updated. Please review and advise whether you still think that there is additional clarification needed here. With the change made to the spec v2.2 I believe we address your concern. Please advise.
