### ISSUE TITLE
Supporting Vendors not on the Vendor List

### ISSUE THREAD

**Issue by GLStephen** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#23]
Is there a process for allowing publishers to support vendors not on the Vendor List? Given requirements to be IAB or other trade organization members as well as the associated fees there are likely to be legitimate vendors that are not on the list yet which do provide value to publishers. Does the Framework have a method by which publishers add their own vendors?

**Comment by LV-799** [comment]
Thanks you

**Comment by LV-799** [comment]
I'm not receiving notifications for this thiread

**Comment by chrispaterson** [comment]
There is no provision for this within the TCF but, some CMPs have home brewed solutions for this.
