### ISSUE TITLE
Typo in Publisher Restrictions Section?

### ISSUE THREAD

**Issue by mindblade** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#231]
Seems like there's a typo in "Publisher Restrictions Section" here - https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#the-core-string

> Eg. if a vendor has Purpose 2 declared as Legitimate Interest but also declares that Purpose as flexible and this field is set to 1, they must then check for the “consent” signal in the VendorConsents section to make a determination on whether they have the legal basis for processing user personal data under that Purpose.

"VendorConsents" needs to be replaced with "PurposesConsent"?

**Comment by tla-sirdata** [comment]
In this example the vendor would normally check his signal in the "Vendor Legitimate Interest" section because it's the default legal basis he has declared. But as there's a publisher restriction set to `1` (require consent), the vendor must check his signal in the "Vendor Consent" section.

**Comment by asr-enid** [comment]
True - we added a more in depth guidance how to determine the presence of a legal basis in the vendor guidance - https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/TCF-Implementation-Guidelines.md#detlegalbasis

As a matter of fact they need to check **both** after determining the applicable legal basis.
