### ISSUE TITLE
Broken for me

### ISSUE THREAD

**Issue by lordmatt** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#235]
On https://quantcast.mgr.consensu.org/ the "change consent" link does nothing for me.
On Tumblr, the consent page fails to load at all.

I am using Chrome on Ubuntu.

**Comment by jawadst** [comment]
@lordmatt This page is specific to Quantcast and not related to this specification so the issue should be reported directly to them.

**Comment by dmdabbs** [comment]
@a2intl at Quantcast can you assist?

**Comment by HeinzBaumann** [comment]
This is for CMP v1 which we deprecated.
