### ISSUE TITLE
CMP behavior understanding

### ISSUE THREAD

**Issue by mdenison** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#239]
I have a few questions regarding CMP behavior, since I haven't found a proper place for questions regarding implementations. I might find answers for my questions here: 

1. The CMP does not control when a custom tracking snippet is loaded, correct? But once the user goes to a page and the tracking snippet is loaded, my logging system from the CDN already received data from that user which I maybe shouldn't be receiving? 

2. Are tracking pixels controlled by a CMP if they get fired or not? Or is a tracking pixel always fired and ${GDPR_CONSENT_XXXX} and ${GDPR} are always set by the CMP? 

3. Is there something like a community board for questions or is github the way to go? I have found many discussion on reddit, stackoverflow and some on github.

**Comment by dmdabbs** [comment]
>The CMP does not control when a custom tracking snippet is loaded, correct?

The TCF specification does not define, nor does it prohibit, a 'tag management' mechanism/role for CMPs. So CMP vendors are free to incorporate such features, and some may have.  

A property owner (publisher) using a TCF-registered Vendor's script-based tags that are built to detect a TCF CMP and read its signals should expect those tags to abide by users' preferences as communicated by the CMP without work on the property's part. Properties should always consult with the Vendor to verify behavior. If the property uses a TCF Vendor's _non-script_ tags (e.g. 'pixels'), then presumably the property handles those. Again, the property should follow the Vendor's instructions, e.g. what signals to read to determine when to embed the pixels and when doing so what TCF signals to pass to the pixel parameters.  

Finally, a property might use vendors that are not registered with the TCF. How a property discloses them to visitors is a matter for the property's legal counsel. The Framework [policies](https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/) do not prohibit CMPs from disclosing non-Framework vendors, but there are restrictions. As above, the property should consult with the vendor.  

>Are tracking pixels controlled by a CMP if they get fired or not? Or is a tracking pixel always fired and ${GDPR_CONSENT_XXXX} and ${GDPR} are always set by the CMP?

If a CMP offers tag management features, then it is reasonable to expect a 'macro substitution' facility to pass TCF signals to embedded content. CMP documentation should address this. 

>Is there something like a community board for questions or is github the way to go? I have found many discussion on reddit, stackoverflow and some on github.

Yes, this repo is the TCF/TechLab's public venue for addressing issues/questions. 

If there are Q&A you feel would improve the [Implementation Guidelines](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/TCF-Implementation-Guidelines.md), then please suggest a PR.
