### ISSUE TITLE
Vendor info list link is broken

### ISSUE THREAD

**Issue by mmndaniel** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#245]
The [docs mentions](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md#what-is-the-url-for-vendor-info-ad-serving-and-asset-domains-for-vendors-in-the-gvl) a link for the vendor info file at: https://vendorlist.consensu.org/vendorinfo.json, but apparently it's broken. Could be be fixed, or is it available somewhere else?

**Comment by dmdabbs** [comment]
That's the TCF v1.1 specification. IAB Europe has deprecated that version and no longer publishes a 1.1 GVL at that url.
The current, active GVL url is in the latest specification: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md.

**Comment by mmndaniel** [comment]
thanks @dmdabbs! your'e right regards the GVL version, but I was looking for the vendor info file, specifically the AdServers property, because I want to know which domains is actually used by each vendor in the GVL. Is there an equivalent for V2?

**Comment by dtbarne** [comment]
I was searching for this too. The TCF2 version is here:
https://vendorlist.consensu.org/v2/vendor-list.json

From:
https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#where-can-i-access-the-global-vendor-list
