### ISSUE TITLE
Allowing Special Purposes only on basis of LegInt

### ISSUE THREAD

**Issue by CaptSnooze** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#252]
For a vendor, who works **only on consent** for **regular purposes,** but uses a also a **special purpose** (where basis is always legInt) such as (GVL entry):

`<some id>":{"id":<some vendor id>,"name":"<some vendor name>","purposes":[1,7,9],"legIntPurposes":[],"flexiblePurposes":[],"specialPurposes":[1],"features":[],"specialFeatures":[],"policyUrl":"<some policy url>","deletedDate":"2020-09-14T00:00:00Z","cookieMaxAgeSeconds":-100,"usesNonCookieAccess":false}`

- **would the TC String generated by a CMP need to list the vendor in the Vendor Legitimate Interest Section** of the Core TC String, given that the vendor does not ask for nor is granted legInt for any regular purpose?
- assuming the CMP allows special purpose 1, but does not allow any **regular** purpose to be done on legInt basis, and consequently has empty PurposeLITransparency, would it still need to list the vendor in the Vendor Legitimate Interest Section, to signal special purpose are declared to the user and can be done by vendor on legInt?

I couldn't find an answer to this anywhere in specs, Q&As, documentation. Sorry if this is the wrong forum.

(special purposes are explicitly not listed in the PurposesLITransparency)

Thanks!

**Comment by asr-enid** [comment]
See here - https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/#___B_Special_Purposes__

Special Purposes are based on a legitimate interest, but users cannot opt-out / don't need to opt-in, thus they are not reflected explicitly in the signal.

**Comment by CaptSnooze** [comment]
Thanks for your response, yes, that makes sense.
My question is not if the special purpose needs to be in the signal, but whether the **vendor** needs to be listed under in vendorLegitimateInterests - given they only use legInt for special purposes, and do all regular ones on consent.

**Comment by dmdabbs** [comment]
The spec is explicit that the Vendor Legitimate Interest section is reserved for establishing vendors' LI basis for Purposes and not Special Purposes. 

>...Set the bit corresponding to a given vendor to 1 if the CMP has established transparency for that vendor's legitimate interest disclosures for one or more Purposes (not Special Purposes).

In your vendor scenario, one could _infer_ their legal basis to perform Special Purpose 1. If you have a string and the vendor id of interest is referenced/covered somewhere in the string (in a vendor consent, vendor li, 'disclosed vendors segment' or possibly publisher restriction) and assuming that the CMP has per Policies disclosed every Vendor's GVL declarations, then one can infer that the vendor's declaration for the SP(s) was disclosed and the vendor's legal basis established.

**Comment by CaptSnooze** [comment]
great answer, thanks David, Achim!
