### ISSUE TITLE
CMPs Handling cookieRefresh from Device Disclosures

### ISSUE THREAD

**Issue by shortaflip** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#264]
Referencing this documentation: [Device Storage Duration & Access Disclosure](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Device%20storage%20duration%20and%20access%20disclosure.md).

How should CMPs handle a disclosure that is missing the `cookieRefresh` key but is of type `cookie`.  The case being that `cookieRefresh` is required when the disclosure type = `cookie`.  Should we add the `cookieRefresh` key ourselves with a default value of `false`?

**Comment by dmdabbs** [comment]
Thanks for opening this @shortaflip. I'll recap our discussion. 

I believe code that parses/loads deviceDisclosure.json files should not add any value where one was not provided (unless the value has a specified default value).  The attribute would have an undefined value to reflect the file's content. The CMP would disclose all the other valid information for the file entry.  

As for what CMPs should display in this or similar cases, @alex we should get TCF MO guidance for the specification.  I will get feedback in this week's Framework Signals Quality WG agenda.  
cc: @Facens , @lon-pilot-mpf

**Comment by shortaflip** [comment]
@dmdabbs, let me make sure that I am understanding it correct.  The parsed object should contain the key but the value would be undefined?

**Comment by dmdabbs** [comment]
Hi @shortaflip . Discussion in today's WG meeting the consensus was that CMPs or library code return the value _undefined_ when this attribute is absent. CMPs are free to display that as deem appropriate.
