### ISSUE TITLE
Missing stack 14 in polish translations

### ISSUE THREAD

**Issue by DianeJane** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#265]
Steps:

- Access polish translations on https://vendor-list.consensu.org/v2/purposes-pl.json
- Check stack 14

Actual :
stack 14 is missing
<img width="981" alt="Screen Shot 2021-03-04 at 5 34 41 PM" src="https://user-images.githubusercontent.com/6456249/109943305-031b4680-7d10-11eb-9146-a61134b52a38.png">

Expected:
stack 14 translation should exist

for comparison, here is the french translations https://vendor-list.consensu.org/v2/purposes-fr.json
<img width="987" alt="Screen Shot 2021-03-04 at 5 35 00 PM" src="https://user-images.githubusercontent.com/6456249/109943509-3cec4d00-7d10-11eb-8da2-b5586f25a9c3.png">

**Comment by dmdabbs** [comment]
Hello @DianeJane. I will forward your issue to the folks at the TCF Managing Organisation.

**Comment by DianeJane** [comment]
Any updates on this?

**Comment by anderagakura** [comment]
@DianeJane I did not notice you but we were working it and now it's solved
![Capture d’écran 2022-03-18 à 09 49 02](https://user-images.githubusercontent.com/37783949/158967393-46d74b94-96bf-4642-b28e-37ae89639345.png)
