### ISSUE TITLE
https://vendorlist.consensu.org/v2/vendor-list.json link is broken

### ISSUE THREAD

**Issue by jmalinens** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#268]
Apparently now it is located in:

https://vendor-list.consensu.org/v2/vendor-list.json

but documentation is not updated.

Probably some apps are broken now because many use it as source for vendor list

Is there any reason for subdomain rename? :)

maybe adding redirect from old source is an option

**Comment by dmdabbs** [comment]
Hello. The v2 specification is up-to-date with the revised domain:

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#where-can-i-access-the-global-vendor-list

The name change and motivation were announced in December and also e-mailed to participants:
https://iabeurope.eu/cmp-vendor-notifications/

**Comment by jmalinens** [comment]
thanks, looks like I was out of the loop
