### ISSUE TITLE
Conflict of interest

### ISSUE THREAD

**Issue by paton** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#3]
The most significant flaw here are the names of the companies under the License section.

A "Transparency and Consent Framework" will be heavily scrutinized and discredited if published by companies who have business models that seem to depend on the lack of transparency and the lack of consent.

Initiatives towards self-regulation within the industry is an amazing step in the right direction, but ultimately the clear conflict of interest will overshadow the substance, for better or worse.

/cc @gobengo

**Comment by typedformiles** [comment]
@paton agreed but only fair to acknowledge that DMG Media and Oath are listed, both of whom should be considered Data Controllers with valid path to consent in their publishing businesses.

The broader support base is almost 100% adtech middle-men, which as you say could lead to the initiative being discredited.

**Comment by jenniferIAB** [comment]
Publishers are acknowledging and adopting the Transparency and Consent Framework. https://iabtechlab.com/press-releases/iab-europe-iab-tech-lab-release-cross-industry-transparency-consent-framework-for-adoption/ And stay tuned for continued endorsements from parties across the industry...

**Comment by ydennisy** [comment]
Why is this issue being closed, this should be a place to discuss to ensure we have good adoption rates and we can bring in various ideas.
