### ISSUE TITLE
Problem with Onetrust AMP Consensu Endpoint

### ISSUE THREAD

**Issue by LightManEye** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#309]
Hi,
the endpoint URL for manage TCF in onetrust CMP have the ssl certificate expired... on 13 Jan.

https://amp.onetrust.mgr.consensu.org/

All the websites with AMP and Onetrust CMP are broken from yesterday.

Who should renew the certificate?

thanks

**Comment by jawadst** [comment]
@LightManEye The consensu.org domain was retired a while ago and is not used by the TCF anymore. I'd suggest reaching out to Onetrust as it's on CMPs to provide alternative solutions.
