### ISSUE TITLE
PHP Consent Implementation

### ISSUE THREAD

**Issue by achrafSallemi** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#31]
Hi,
We need the implementation of the Consent on PHP language. 
Are you planning to release it in the near future ? 

Thanks

**Comment by chrispaterson** [comment]
Are you talking about the Consent String SDK?  I didn't have a plan to do a PHP implementation, but all of the Consent String SDK implementations have been a community effort.  So if you'd like to take a crack at translating the [Consent String SDK specification](https://docs.google.com/document/d/1csswKXYx6aK1MwQazX92G_t02zlKS7Xiolycm1V1mv4/edit?usp=sharing) to PHP and create a repo and I can have the IAB open up a repo for you to add a pull request to.
