### ISSUE TITLE
Additional Vendor Information List Specification - broken link

### ISSUE THREAD

**Issue by mattpr** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#317]
Link in [docs](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/Additional%20Vendor%20Information%20List%20Specification.md#where-can-i-access-the-additional-vendor-information-list)...

> The Additional Vendor Information List is in JSON format and the current version at any given time can be retrieved using the following URL structure:
> `https://vendor-list.consensu.org/v2/additional-vendor-information-list.json`

...is broken.

![image](https://user-images.githubusercontent.com/1196252/158179971-209ce5bc-cde6-4921-bf70-80ff97efc3e0.png)

As an aside...regarding the email that went out (2022-03-14) about updating our registration to fill in the new fields....
Looks like registration form hasn't been updated yet (maybe the email was sent prematurely?).

- `deviceStorageDisclosureUrl` - present but not a required field.
- "Territorial scope", "Environment", "Type of service", "International transfer" - fields not present in either page of registration form

**Comment by avuim** [comment]
as mentioned in the mail of today "Vendors must apply the necessary changes to their registration by 14th July 2022". I don't think that the additional vendor information list JSON will be public available before.

The deviceStorageDisclousreUrl is marked in the vendor form as mandatory "*" as far as I can see and the given new fields are available in the B2B disclosure section of https://register.consensu.org/Home/ShowExistingData
