### ISSUE TITLE
iab tcf library for ios development 

### ISSUE THREAD

**Issue by devendrashewale3** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#326]
I am looking for library of iab tcf  V2 for iOS environment I could not find it any GitHub repositories however i am using iabtcf-java V2 library for android app

**Comment by dmdabbs** [comment]
Perhaps someone has updated 

https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Swift

**Comment by dmdabbs** [comment]
I don't know, @devendrashewale3. Just forwarding the repo ref for your review.

**Comment by HeinzBaumann** [comment]
We don't have a iOS library that supports v2.x. Unless there is a volunteer to provide it to the community there won't be one anytime soon. Several CMP providers support mobile and have SDKs for iOS and Android.
