### ISSUE TITLE
Clarification TCF v2.2: GVL Policy Version - Validity of existing strings.

### ISSUE THREAD

**Issue by 0megaD** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#335]
[This pull request](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/334) contains the following change:

> From the corresponding field in the
        <a href="#the-global-vendor-list">GVL</a> that was used for
        obtaining consent. A new policy version invalidates existing strings
        and requires CMPs to re-establish transparency and consent from
        users.

to

> From the corresponding field in the
        <a href="#the-global-vendor-list">GVL</a> that was used for
        obtaining consent.

Does detecting a new policy version no longer invalidate existing strings? Or has this information simply been moved elsewhere?

**Comment by HeinzBaumann** [comment]
Thank  you Daniel for the question. There is a Policy change that goes along with this, that removes the requirement to prompt the CMP when the policy version changes.

**Comment by 0megaD** [comment]
Alright, that's fully clear then. Thanks for the quick reply. 😄
