### ISSUE TITLE
Google’s Additional Consent Mode

### ISSUE THREAD

**Issue by rlankhorst** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#336]
We are preparing for the certification process for Google's new CMP format, and doing some research on the required changes. 

Based on this article about Google’s Additional Consent Mode:
https://support.google.com/admanager/answer/9681920?hl=en

The article proposes to extend the tcData string with the acString. Similar to the tcString, one would then expect the cmpApi to include models and functions to add the generated tcString. However, this does not seem to be included yet in the current cmpApi. 

Am I misunderstanding the above article, and should we somehow include the acString in another manner, or is this very preliminary, and just not included in the current version of the cmpApi?

**Comment by HeinzBaumann** [comment]
There are no plan to include the Google acString as part of the tcString. the Google acString will need to be handled separately from TCF as it is a separate thing. Not sure whether GPP might support acString or not. That would be a question for the GPP forum.
