### ISSUE TITLE
Consent String via postMessage

### ISSUE THREAD

**Issue by verasitytech** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#337]
Context: scenario where the code seeking for the consent from the user is embedded into publisher's page using an iframe and origin of the iframe differs from the publisher's domain. TCF 2.0 has a great feature to deal with such case where the consent string is passed via the postMessage between main window and an iframe.

Does deprecation of getTCData break the above mentioned feature? 
What would be the alternative way for an iframe content to request the consent string given that the cross origin policy does not allow scripts to interact directly?

**Comment by janwinkler** [comment]
the postMessage functionality will remain the same, only that you shall now call the addEventListener command and that you need to consider that your callback function may be called multiple times
