### ISSUE TITLE
This Library supports TCFV2.2? 

### ISSUE THREAD

**Issue by NicolasLaverde** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#339]
This Library supports TCFV2.2?  cause you mention in redmi verison 1, 2 but not 2.2 or 3 
Also according with TCFV2.2 specifications you don't support more getTCData. What need to do for this update? 
https://iabeurope.eu/wp-content/uploads/2023/05/FAQ_-TCF-v2.2-.pdf

**Comment by HeinzBaumann** [comment]
@NicolasLaverde since your original post, yes the library supports TCF v2.2. Please see the updated specs and guidelines for the changes. Regarding getTCData removal, you will need to use an eventListener to get the up to date tcData object.
