### ISSUE TITLE
__tcfapi event listener returns null for tcData

### ISSUE THREAD

**Issue by ocm-peter** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#341]
Hello,

Since today we noticed that the call to __tcfapi as so:

`__tcfapi('addEventListener', 2, function(tcData, success) { console.log('cmp responded:', tcData, success);});`

will return null for tcData.

This has affected numerous websites and publishers have been raging for their ad setup.
We are mostly using the Quantcast CMP.

Thank you in advance.

**Comment by ocm-peter** [comment]
There are two cases we've seen this.

https://www.foititikanea.gr and https://parianostypos.gr

Someone must be overwriting the event listener functionality of the __tcfapi library?

**Comment by HeinzBaumann** [comment]
@ocm-peter Did you resolve this with the CMP provider?

**Comment by ocm-peter** [comment]
Yes, it was a conflict with the mootools framework. They should be loading it only on their backend of their CMS, not on the front-end.
