### ISSUE TITLE
Undocumented methods

### ISSUE THREAD

**Issue by rforster-dev** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#350]
We work with SourcePoint and have been adding custom vendors.
Using this documented:

```javascript
__tcfapi('addEventListener', 2, (tcdata, success) => { console.log(tcdata) })
```
Returns the list of IAB vendors and their status under `vendor.consents` and if they are <true/false> but not the custom vendors added.

But using say:
```javascript
function customVendors(data, success) {
    console.log(data, success)
}

// call the __tcfapi() function with callback only
__tcfapi('getCustomVendorConsents', 2, customVendors);
```
Does return the _custom vendors_  can this be added to the documentation? Are there other methods that are not mentioned in the docs? 

Thanks!

**Comment by jawadst** [comment]
This is a SourcePoint-specific implementation and is not part of the TCF specification and is probably not supported by other CMPs

**Comment by rforster-dev** [comment]
Ah I see, my apologies. 

I suppose then there is no scope for this kinda functionality to be part of IABTCF is there?

If not, i'll close this :).

**Comment by jawadst** [comment]
No worries, I just wanted to add some context as I received a notification for your message :)

I'll let somebody from the IAB EU/Tech Lab chime in on whether they want to consider adding support for other features like custom vendors via the `__tcfapi` function.

**Comment by HeinzBaumann** [comment]
This is a custom function that vendor can already add to the tcf api.
