### ISSUE TITLE
Machine readable CMP List

### ISSUE THREAD

**Issue by sammacbeth** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#36]
I was not able to find information if there is a machine-readable version of the [registered CMPs](http://advertisingconsent.eu/iab-europe-transparency-consent-framework-list-of-registered-cmps/) list (equivalent of the [vendorlist.json](https://vendorlist.consensu.org/vendorlist.json) file). Does such a list exist?

This would be useful for building tools which introspect about the consent cookie.

**Comment by dmdabbs** [comment]
Hello @sammacbeth . The IAB now publishes the file you requested. See https://vendorlist.consensu.org/vendorinfo.json

**Comment by jawadst** [comment]
@dmdabbs That is the URL of the vendor list, is the list of CMPs included in there? I can't find it. Thanks!

**Comment by dmdabbs** [comment]
Hello @jawadst. Look closely. The url I posted is the CMP 'vendor info' list. 
Here is the vendor list: https://vendorlist.consensu.org/vendorlist.json

**Comment by chrispaterson** [comment]
There is not one available at this time.  I agree this would be a worthy thing to have.  I'll try to elevate discussion around this in the commit group.

**Comment by nouchy** [comment]
Hi all. https://cmplist.consensu.org/cmp-list.json is now available
