### ISSUE TITLE
Purpose 10: Wrong translation of description/ first illustration in /v3/purposes-de.json

### ISSUE THREAD

**Issue by mredl** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#362]
The first illustration has a wrong translation:

english:
`"10": {
			"id": 10,
			"name": "Develop and improve services",
			"description": "Information about your activity on this service, such as your interaction with ads or content, can be very helpful to improve products and services and to build new products and services based on user interactions, the type of audience, etc. This specific purpose does not include the development or improvement of user profiles and identifiers.",
			"illustrations": [
				"A technology platform working with a social media provider notices a growth in mobile app users, and sees based on their profiles that many of them are connecting through mobile connections. It uses a new technology to deliver ads that are formatted for mobile devices and that are low-bandwidth, to improve their performance.",
				"An advertiser is looking for a way to display ads on a new type of consumer device. It collects information regarding the way users interact with this new kind of device to determine whether it can build a new mechanism for displaying advertising on this type of device."
			]
		},`

german:
`		"10": {
			"id": 10,
			"name": "Entwicklung und Verbesserung der Angebote\n\n",
			"description": "Informationen über Ihre Aktivitäten auf diesem Angebot, wie z. B. Ihre Interaktion mit Anzeigen oder Inhalten, können dabei helfen, Produkte und Angebote zu verbessern und neue Produkte und Angebote zu entwickeln basierend auf Benutzerinteraktionen, der Art der Zielgruppe usw. Dieser Verarbeitungszweck umfasst nicht die Entwicklung, Ergänzung oder Verbesserung von Benutzerprofilen und Kennungen.",
			"illustrations": [
				"Informationen über Ihre Aktivitäten auf diesem Angebot, wie z. B. Ihre Interaktion mit Anzeigen oder Inhalten, können dabei helfen, Produkte und Angebote zu verbessern und neue Produkte und Angebote zu entwickeln basierend auf Benutzerinteraktionen, der Art der Zielgruppe usw. Dieser Verarbeitungszweck umfasst nicht die Entwicklung, Ergänzung oder Verbesserung von Benutzerprofilen und Kennungen.",
				"Ein Werbetreibender sucht nach einer Möglichkeit, Anzeigen auf einem neuartigen Endgerät anzuzeigen. Er sammelt Informationen darüber, wie Benutzer mit dieser neuen Art von Endgerät interagieren, um herauszufinden, ob er einen neuen Mechanismus für die Anzeige von Werbung auf dieser Art von Endgerät entwickeln kann."
			]
		},`

the first illustration should be like:
`Eine Technologieplattform, die mit einem Social-Media-Anbieter zusammenarbeitet, stellt einen Anstieg der Nutzer mobiler Apps fest und stellt anhand ihrer Profile fest, dass viele von ihnen über mobile Verbindungen eine Verbindung herstellen. Es nutzt eine neue Technologie, um Anzeigen zu liefern, die für Mobilgeräte formatiert sind und eine geringe Bandbreite haben, um deren Leistung zu verbessern.`

**Comment by HeinzBaumann** [comment]
@mredl Thank you for reporting this. We will update the translation. It should be updated with this weeks (Thursday's) GVL update. I also removed these \n\n from all purpose names in the German translation.
