### ISSUE TITLE
English translation is not presented in the translations list

### ISSUE THREAD

**Issue by olizarevichroman** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#368]
I've noticed that the translation list (https://register.consensu.org/Translation) doesn't include English translation.
I understand that English is default and can be extracted from a GVL, but GVL and translation are considered as different entities.

When I'm working with translations it's weird that I have to know that specifically for English I have to work with GVL entity.

**Comment by HeinzBaumann** [comment]
@olizarevichroman This is nice suggestion. Let me see whether we can add English to the list of translations.

**Comment by olizarevichroman** [comment]
> @olizarevichroman This is nice suggestion. Let me see whether we can add English to the list of translations.

Thanks!

@HeinzBaumann Also as food for thought -  it would be nice to have an endpoint that returns a list of available translations. I suppose that a lot of consumers of translations have a larger set of supported languages in their applications. And all of them, i guess, have a quiet similar logic to handle that. All of them should have a copy of languages that officially translated. If one of application's language is not officially supported then fallback language is used. Once a new language added - applications should update their copy list manually.

It seems more convenient to request IAB about supported languages and do not have a copy of it. Thanks 🙂

**Comment by mujuonly** [comment]
<img width="1510" alt="image" src="https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/assets/459367/486b8493-ba8a-42b2-8775-34bae4b8518a">
Chrome feature maybe useful to translate all in one go :)

**Comment by olizarevichroman** [comment]
@HeinzBaumann Hi, do you have any updates?

**Comment by HeinzBaumann** [comment]
@mujuonly The additional of English is getting implemented along with a dozen other languages we added to TCF. 
The end point to return the list of languages is in out backlog. We pick that up next time we do an major update to the registration portal.

**Comment by HeinzBaumann** [comment]
This was fixed last week. You now find the English JSON file under transltions.
