### ISSUE TITLE
cmp form doesnt include all vendors

### ISSUE THREAD

**Issue by ronigottesman** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#377]
Hi, Im facing the following issue-
when I entered to some sites their cmp doesn't include all vendors.  
if the user select "accept all" the vendors that did not appear in the form are not found in TCString.getVendorConsent().

now if I want to show on that site item that his tracking pixel include vendor that did not appears in the cmp- what should I do?
I dont want to block the item since the user select "accept all".

is there a way to know if the user select accept all from the TCString?
or to know who are the vendors that appears in the form?

thank you!

**Comment by HeinzBaumann** [comment]
The Accept All applies to all vendors disclosed in the CMP not to all vendors in the GVL. The tcString contains only consent for the vendors that the user has consent to (in your case through Accept All). Signals from or signaling to vendors that do not have consent in the tcString should be treated as not consent and appropriate action should be taken.

**Comment by ronigottesman** [comment]
thank you (:
