### ISSUE TITLE
Implementing with safeframe

### ISSUE THREAD

**Issue by mfrachet** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#38]
Hi,

I'm actually working on porting and using safeframe on React for GDPR purposes ([react-safeframe](https://github.com/mfrachet/react-safeframe)) but it's completely unclear in my mind what the caller should do to be able to use `cmp` inside the safeframe.

For now, on my host side, I'm having something like

```javascript
import React from "react";
import Safeframe from "react-safeframe";

const conf = {/* not important for now */};

window.__cmp = function(Command, Parameter, Callback) {
  console.log('Absolutely never passing on here');
  Callback();
};

const App = () => (
  <Safeframe conf={conf} frameUrl="http://localhost:3000/iframe.js" />
);

export default App;
```

And on my iframe side:

```javascript
console.log("Vendor is available");

function sf_callback(msgName, data) {
  console.log(msgName);
}

$sf.ext.register(300, 250, sf_callback);
$sf.ext.cmp("getVendorConsents");
```

For now the `Vendor is available` is well displayed.

But first, `sf.ext.cmp` is never defined (why or how should I process ?), and then, nothing happens.

How can we manage to make this work ? Is this possible to create an example using safeframes ?

Thank you

**Comment by gcbw** [comment]
No vendor ended up implementing the $sf.ext.cmp extension. Some implemented a transparent proxy to the main __cmp() method on the publisher page, which is a better solution that requires no special concerns from the vendors/ads (besides adopting the regular, non-safeframe, spec). 

I'm formalizing the proxy on v2.
