### ISSUE TITLE
Vendorlist URI returning 403 access denied

### ISSUE THREAD

**Issue by sebensch** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#381]
As per specification, the latest GVL should be available under https://vendorlist.consensu.org/vendorlist.json. The URI returns a Access Denied response. The version-specific URI on the other hand works fine; see https://vendorlist.consensu.org/v3/vendor-list.json. 

```
curl -I 'https://vendorlist.consensu.org/vendorlist.json'
HTTP/2 403 
content-type: application/xml
date: Mon, 14 Oct 2024 14:34:00 GMT
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 2f5456dbfb45d29444848e5c1ebf1414.cloudfront.net (CloudFront)
x-amz-cf-pop: LAX54-P2
x-amz-cf-id: gd9lqozc6kXm9uF-uvh4ZpAWTehAHSzHqWDMoqfoo8EkVQOIpAc5-w==
```

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/a4b5d101fe3dffcf98d4cb2d0aa8e378c4a76016/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md?plain=1#L153C48-L153C95

**Comment by HeinzBaumann** [comment]
You were looking at the v1.1 specification which is no longer valid. If you consult the v2 specification you will find a note that https://vendorlist.consensu.org/vendorlist.json is not supported with V2. Closing this issue.
