### ISSUE TITLE
Go Vendor Consent String implementation relies on package 'go-bits' which doesn't properly handle errors

### ISSUE THREAD

**Issue by momer** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#41]
The Go implementation of the Vendor Consent String relies on a package, ['go-bits'](https://github.com/rupertchen/go-bits), which has poor error handling that will `panic` in error scenarios, instead of returning the error and allowing the handler to handle it appropriately.

https://github.com/rupertchen/go-bits/blob/master/bits.go#L66-L104

**Comment by chrispaterson** [comment]
I wasn't aware that there was a "Go Vendor Consent String"?

**Comment by momer** [comment]
@chrispaterson reworded my post, but made the issue on the wrong repo!
