### ISSUE TITLE
customPurposeID starts at different numbers in different specs

### ISSUE THREAD

**Issue by nhagen** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#42]
Unclear if this is an oversight, or just not documented, but we have these two statements:

From CMP API v1.1:

> PurposeId's 1-24 indicate standard purposes, while 25-88 indicate custom (publisher-configured) purposes. 

From Consent String and Vendor List Format:

> CustomPurposeIds are numbered 1 to NumberCustomPurposes.

If the publisher is depending on the `customPurposeId` that they configured, they will need to know to check it with a 24 point offset in the `PublisherConsents` object, right? This isn't documented anywhere that the `customPurposeId` would be different across contexts.

**Comment by chrispaterson** [comment]
I think the publisher was envisioned to access the custom purposes they would use the __cmp api and get a PublisherConsents response:
https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md#publisherconsents-

which separates out the custom purposes and the standards and returns them as boolean values.  The idea was to keep publishers from having to parse a bit string.

**Comment by chrispaterson** [comment]
There are two different strings.  CustomPurposeIds are only in the publisher consent string which is different than the regular old consent string.
