### ISSUE TITLE
getVendorConsents and purposeConsents

### ISSUE THREAD

**Issue by mnbroatch** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#43]
The description of the getVendorConsents command does not mention the purposeConsents property of the VendorConsents object. In fact none of the command descriptions mention this property. Is the VendorConsents object passed to the callback of a getVendorConsents __cmp() call required to include information about all consented purposes?

**Comment by chrispaterson** [comment]
the getVendorConsents command is implemented this way:

`__cmp("getVendorConsents", [optional parameter], function(VendorConsents) {
});`

and that VendorConsents object is defined with the purposes consents as follows:
`{ 

  metadata: [base64url-encoded](https://tools.ietf.org/html/rfc4648#section-5) string (header data from the vendor consent format, as described below),

  gdprApplies: *Boolean*,

  hasGlobalScope: *Boolean,  // true if the vendor consent data is retrieved from the global cookie, false if a publisher-specific (or publisher-group-specific) cookie*

  purposeConsents: {

    *purposeId*: *consentBoolean*,

    ?

  },

  vendorConsents: { 

    *vendorId* : *consentBoolean*, 

    ?

  },

}`
https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md#vendorconsents-
