### ISSUE TITLE
IFrame: Why should one wrap the __cmp call into a postMessage / message event?

### ISSUE THREAD

**Issue by sboligatus** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#54]
To whom it may concern,

in section [Without safeFrames, using postMessage](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md#postmessage) of the CMP JS API v1.1 Final you discuss how the __cmp
API can be called **from within an iframe** by sending a postMessage to the
__cmpLocator frame.

Would you please let us know whether you have considered calling the
parent's __cmp API directly without wrapping the call into a postMessage /
message event layer?

If so, why do you suggest the wrapping?

Using the CMP API provided by http://oil.axelspringer.com/ we located the parent window
containing the __cmp function in a way similar to locating the __cmpLocator.
Then we have called that function and received the response successfully.

We are looking forward to read your answer.

Kind Regards
Stefan Boos

--
  Stefan Boos
  Senior Software Developer

  Ligatus D-A-CH
  Ligatus GmbH, Christophstraße 19, 50670 Cologne
  Executive Board: Klaus Ludemann, Arne Wolter

**Comment by jawadst** [comment]
@sboligatus You cannot call a function on another frame that runs on a different domain (ie cross-origin function call) which is very common in advertising. `postMessage` is the standard solution to that issue.

**Comment by sboligatus** [comment]
Hi @jawadst, thanks for your quick response. That helped us.

Actually we just encountered this problem ;-)

More information about this topic (for other readers) is given in [this StackOverflow thread](https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame).
