### ISSUE TITLE
Cookies still being collected

### ISSUE THREAD

**Issue by vfstomas** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#59]
Hey guys,

can you please confirm how the cookies are being managed once preferences have been set.

I found that all cookies are loaded at first in spite of the cookie manager shows to set preferences.
Once preferences are set, all cookies are still there when I browse thought the website and pages. The feeling that I am getting is that the cookie manager is not really managing my preferences and most probably because they are all already used in first instance.

Thank you.

**Comment by vfstomas** [comment]
Forbes.com could be a good example. Solution by Truste

**Comment by chrispaterson** [comment]
@blakebrannon is right, it depends on the CMP.  The TCF itself doesn't actually dictate this.
