### ISSUE TITLE
Change preferences again

### ISSUE THREAD

**Issue by vfstomas** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#60]
Hi team,

would be great if the popup didn't disappeared completely after preferences are set. User should have the option to change his/her mind and activate/de-activate as pleased.
A good example is [CivikUk ](https://www.civicuk.com/)solution.

thanks

**Comment by chrispaterson** [comment]
Is this in reference to the reference implementation?

**Comment by chrispaterson** [comment]
This is determined on a CMP by CMP basis.
