### ISSUE TITLE
typo squatter on wwwmirando.de ?

### ISSUE THREAD

**Issue by dmarti** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#65]
In the vendor list entry for  "Mirando GmbH &amp; Co KG" the privacy policy is: `https://wwwmirando.de/datenschutz/`

Should this be `www.mirando.de` instead of `wwwmirando.de`?

**Comment by chrispaterson** [comment]
Looks like that link leads to an actual privacy policy...

**Comment by dmarti** [comment]
The privacy policy looks real, but the domain is wwwmirando.de which does not appear to be the same company as mirando.de. The wwwmirando.de home page is just a blog template with "full album download" links.
