### ISSUE TITLE
Possible assertion error in postMessage implementation

### ISSUE THREAD

**Issue by enys** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#74]
In https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md#without-safeframes-using-postmessage-

`cmpCallbacks[i.callId](i.returnValue, i.success);
`

The callback array is not protected against multiple re-call. This can cause a  `not a function` assertion.
Would you be open to a PR ?

**Comment by dmdabbs** [comment]
_The callback array is not protected against multiple re-call. This can cause a not a function assertion._
Yes, it is not protected. If you've run into this, did you determine the cause for why you are getting two postMessage calls for the same id?

**Comment by enys** [comment]
Totally missed the notification for the answer on this. Will probably wait for V2 to check if the problem is still around then. Sorry about that.
