### ISSUE TITLE
Discrepancy between 1.1 specification and published vendor list JSON purposes and features

### ISSUE THREAD

**Issue by pdehaye** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#79]
In previous issues that I opened but were closed without action (such as #68 and #69), I pointed out that the IAB Consent Framework was bundling two consents into one (and misleading spec readers in communicating what they were doing). 

The 50M EUR fine today against Google by the CNIL confirms this ([see item 160](https://www.cnil.fr/sites/default/files/atoms/files/san-2019-001_21-01-2019.pdf)). 

Please reopen the associated issues, lest you want to expose your members to similar fines (particularly, I presume, the French ones).

**Comment by chrispaterson** [comment]
As @jawadst has stated, policy people don't look at this GitHub repository.  Please channel your concerns to the appropriate place.

**Comment by chrispaterson** [comment]
@pdehaye I can see now what you are getting at.  However, your pull request #66 doesn't actually change the text to read exactly as the vendorlist does right now, which is:

> "name": "Personalisation",
> "description": "The collection and processing of information about your use of this service to subsequently personalise advertising and/or content for you in other contexts, such as on other websites or apps, over time. Typically, the content of the site or app is used to make inferences about your interests, which inform future selection of advertising and/or content."

Also, Google is not currently using the TCF, so their fine has nothing to do with the TCF and doesn't "invalidate" the TCF.  I will try and fix the issue, thanks for raising it.

**Comment by pdehaye** [comment]
Thank you. 

A few comments/questions:
* What's the process to get this now to the official spec? [This](http://advertisingconsent.eu/publishers/) still points to the old one. 
* Are you sure this is the right way to make this change? In particular for the second, this drastically changes the nature of the consent obtained. What is the process to invalidate the improperly obtained past consents? 
* For consent id 2 your fix removes this version:
> The collection and processing of information about user of a site to subsequently personalize advertising for them in other contexts, i.e. on other sites or apps, over time. Typically, the content of the site or app is used to make inferences about user interests, which inform future selections.</td>

and instead uses this version everywhere: 

> The collection and processing of information about your use of this service to subsequently personalise advertising and/or content for you in other contexts, such as on other websites or apps, over time. Typically, the content of the site or app is used to make inferences about your interests, which inform future selection of advertising and/or content.

In particular this fix makes it clear that the consent id 2 is tied to two purposes: content personalisation and advertising personalisation (this is even more glaring in light of the fact that consent ids 3 and 4 are decoupled between content and advertising selection, reporting and delivery). 

The CNIL just fined Google for exactly that, see [item 160](https://www.cnil.fr/sites/default/files/atoms/files/san-2019-001_21-01-2019.pdf). The operating keyword in French is "univoque", I suggest you search in English for "specific purpose CNIL Google consent", and pick your favorite source. 

I think the legal exposure for corporate users of the IAB Consent Framework is there whenever:
* a European data subject provides this particular consent (id 2), regardless of where the corporate user is established,  or
* whenever a European corporate user of the IAB Consent Framework relies on consent 2. 

Focusing on France for the second point, in the [vendor list](https://vendorlist.consensu.org/vendorlist.json) I can pick out (through `.fr` extension):

>  {"id":331,"name":"ad6media","policyUrl":"https://www.ad6media.fr/privacy","purposeIds":[1,2,4],"legIntPurposeIds":[3,5],"featureIds":[2,3]}

and

> {"id":274,"name":"Golden Bees","policyUrl":"http://goldenbees.fr/notre-politique-de-confidentialite/","purposeIds":[1,2,3,4,5],"legIntPurposeIds":[],"featureIds":[]}

as being problematic, for instance.

**Comment by pdehaye** [comment]
Thanks for the response. 

It comes down to what has precedence on the website, and to whom.  Indeed the [policy document](http://www.iabeurope.eu/tcfdocuments/documents/legal/currenttcfpolicyFINAL.pdf) was correct,  but [over here](http://advertisingconsent.eu/publishers/) the link above it is to a *particular commit* of the file you are correcting, with the link titled "CONSENT STRING AND GLOBAL VENDOR LIST FORMAT SPEC V1.1​". That's still "wrong" even if your commits go through: the link should go to the current version, including your correction.
