### ISSUE TITLE
"Data Controller" instead of "Vendor"

### ISSUE THREAD

**Issue by JaapFrancke** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#83]
The API uses the term "vendor" in various areas. Since the aim is to facilitate GDPR compliency, I think it would be better to use GDPR terminology where possible.
In case of 'vendor', the better term would be 'Data Controller', which can be a vendor but not necessarily. This brings the following benefits:
- Using such terminology makes the API's more clear to anyone with GDPR-knowledge.
- The APIs may facailitate a wider range of use cases
- The semantics for attributes in schema definitions can more easily be defined by cut&pasting relevant quotes from the GDPR.

**Comment by wolfschild** [comment]
Actually, vendors are almost always “data processors” not “data controllers”. I agree with the change, but it should be “data processor” for vendors.

**Comment by wittjill** [comment]
these are definitions within TCF: https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/#_________Chapter_III_Policies_for_Vendors___________
