### ISSUE TITLE
[question] How can I find a list of all purposeIds and what they mean?

### ISSUE THREAD

**Issue by ioweb-gr** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#89]
Hi,
how can I view a detailed list of all purposes with their respective ids and their meanings? I would like to study them so I can integrate various callback functions but I don't seem to find anything related in the docs. 

Just that by using getPublisherConsents I will retrieve a list of purpose Ids in my callback function but without explaining what each purpose id is.

**Comment by danielrsantana** [comment]
You can either find it from the latest version https://vendorlist.consensu.org/vendorlist.json or you can also define the desired version you want the list https://vendorlist.consensu.org/v-{version}/vendorlist.json.

For more information : https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md#what-are-the-urls-for-the-vendor-and-standard-purposes-lists-
