### ISSUE TITLE
Error: ConsentString - Unsupported version 27 in the string to decode

### ISSUE THREAD

**Issue by ebenStickney** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#90]
I don't know if this an appropriate place to put this issue.  But I have certain browsers which can't close their consent banner because of this error: 
`Error: ConsentString - Unsupported version 27 in the string to decode` It is a pretty unpleasant UX for our users and I can't figure out what is going on.  
It is only happening when accessing our desktop site via iOS or on a Mac using safari.  when I decode the consent string, I don't see 27 as a value for any of the object properties, so I don't know what "version this code is pointing to.  Anyone seen this before?

**Comment by paooolino** [comment]
I'm struggling with a similar issue.
I'm getting "Uncaught Error: ConsentString - Unsupported version 0 in the string to decode".
The consent string I get is "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA".
I get this with both Chrome and Firefox BUT only on a specific website.
I fear there's something with the browser compatibility mode while executing JS.

**Comment by paooolino** [comment]
my problem is caused by this version of Prototype.js

Prototype JavaScript framework, version 1.6.0.2

more on this later

**Comment by paooolino** [comment]
I found my issue was caused by the prototype.js overwriting the Array.reduce() method which is defined as follows

```
  reduce: function() {
    return this.length > 1 ? this : this[0];
  },
```

to solve this, I will re-assign the correct native implementation of Array.reduce() on top of my CMP code

```  
  reduce: function() {
    return this.length > 1 ? this : this[0];
  },
```

hope this may help you as well.
