### ISSUE TITLE
Meaning of "success" in callbacks?

### ISSUE THREAD

**Issue by mindplay-dk** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#92]
Commands such as `getVendorConsents` provide a `success` flag to the callback.

I didn't find anything in the documentation explaining the purpose of this flag?

Version 1.1 of the API spec merely states:

> The boolean success parameter passed to the callback indicates whether the call to getVendorConsents() was successful.

Successful at what?

When (or under what conditions) would this command be expected to fail?

More importantly, how should client code interpret a failed command?

Presumably, client code needs to check the success flag before doing anything with the `VendorConsents` object?

How should the callback behave if invoked with `success` set to `false`? What does it mean?

**Comment by wittjill** [comment]
closing since this is v1.1 specific
