### ISSUE TITLE
Comments on the TCF v2 API

### ISSUE THREAD

**Issue by mindplay-dk** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#93]
I'd like to provide some technical feedback on the TCF v2 API.

Based on my experience with version 1 of the API, I feel the new API has taken the command approach from the first version of the API and made it worse.

I'd like to question the benefits of a command-based API - per the example in the v2 spec:

```js
__tcfapi('getTCData', 2, (tcData, success) => {
  if(success) {
    // do something with tcData
  } else {
    // do something else
  }
}, [1,2,3]);
```

I find this approach to be fragile, as demonstrated by the documentation for this particular command:

> A value of `false` will be passed as the argument to the success callback parameter if an invalid `verdorIds` argument is passed with this command. An invalid `vendorIds` argument would constitute anything other than an array of positive integers.

In other words, *client* code is burdened with the responsibility of checking whether the client code *itself* passed valid arguments. It effectively makes argument checking optional.

I understand why it was implemented this way: you want to be able to preload a simple stub, and so of course we can't have the command call itself throwing an error for the call, since the command implementation might not actually be loaded yet.

But there's a much simpler way to defer calls to an API:

```js
__tcfapi(2, tc => {
  try {
    var tcData = tc.getTCData([1,2,3]);
    // do something with tcData
  } catch (e) {
    // do something else
  }
});
```

In other words, instead of queing and deferring individual commands, simply defer all interactions with the API entirely. (The edge case here is `ping`, to which the stub needs to respond immediately, so this could be changed to e.g. `__tcfapi.ping()`)

This leads to more readable code: the arguments to the function are supplied with the actual call `tc.getTCData([1,2,3])`, rather than arguments floating around at the tail of the call, *after* the body of the callback.

It also leads to a more traditional JavaScript API: you invoke commands by merely calling a function - for synchronous commands, you can use the traditional exception-handling approach, as in the example above, while (much more likely) you wouldn't want to handle errors in your own client code at all, and likely want to simplify it even further:

```js
__tcfapi(2, tc => {
  var tcData = tc.getTCData([1,2,3]);
  // do something with tcData
});
```

This is much safer and much closer to how most normal JavaScript APIs function: if you supply the wrong arguments, you get an exception. Error handling is only necessary or relevant if, for example, the argument is dynamic - in this example, as in most real use-cases, it's just a static array of values, and the error-handling mechanism really is only something you rely on to tell you (immediately) that there's something wrong with your client code.

The stub for something like this ought to be much simpler - along the lines of:

```js
window.__tcfapi = window.__tcfapi || (function() {
  var queue = [];
  var api = cb => queue.push(cb);
  api.queue = queue;
  api.ping = () => ({
    gdprApplies: gdprApplies,
    cmpLoaded: false,
    apiVersion: '2.0',
  });
  return api;
})();
```

I realize there's a bit more to it than that, but it's greatly simplified. The full implementation merely picks up `window.__tcfapi.queue`, replaces `window.__tcfapi` with the full implementation, and initializes by invoking every function in the queue.

The stub should be small enough to minify and embed directly on the page for better startup time - many stubs for version 1 of the API are already large enough that they're supplied as a separate, external script, and the version 2 sample stub is even more complex.

Because it's trivial, you can guarantee it'll never need to change, at least for the same version of the API - embedding it directly on the page is easy and safe. (You might as well just make it part of the standard, so that individual vendors don't need to supply their own stubs - and publishers can safely insert this on their page and not worry about switching to a vendor that requires a different proprietary stub, for example.)

On a side note, I don't know what good the `apiVersion` field in the `PingResult` does. In the proposed API, you have to supply the API version number yourself to invoke the `ping` command - you invoke it with a version `number` and it returns a `string`, which is difficult to wor with, if you wanted to test for the exact version number. Either way, if I have to specify the version number to get the version number, well -- it's probably better to leave this command as separate from the main API, since it isn't supposed to queue up like other commands, and the implementation is always going to be a simple synchronous function anyhow.

**Comment by chrispaterson** [comment]
Thanks, @mindplay-dk for the extensive feedback.  I just skimmed it – I don't have enough time at the moment to formulate a proper response – but, I think you make some really good points that I would like to review in more detail.

**Comment by mindplay-dk** [comment]
One more thing to consider: when your API accepts a callback, it's never completely apparent when (now vs later) or how many times that callback is going to be called. I've seen several vendors getting this wrong: they execute the callback at the wrong time, or (worse) they execute it more than once.

For example, with regards to `getTCData`, the v2 spec states:

> The callback shall be invoked only once per api call with this command.

Plain API calls don't need written explanations like this - if you're literally just calling a function, it's natural to expect that function to execute and return.

Note that none of this precludes having some API points are *are* asynchronous - if, for example, you wanted to support asynchronous implementations of `getTCData`, you can still do that using Promises:

```
__tcfapi(2, tc => {
  tc.getTCData([1,2,3]).then(data => {
    // do something with tcData
  });
});
```

Promises are also idiomatic to modern JavaScript and support proper exception-handling using either `try-catch` blocks or `.catch()` callbacks, so this approach is just as safe and reliable.

In terms of performance, of course you need to consider expectations and requirements for implementations of the API as well as for use-case: do you *want* to allow asynchronous implementations of certain methods, or is an implementation required/expected to be fully initialized and capable of immediate (blocking) returns?

Allowing asynchronous implementations is more flexible, but also allows for implementations with somewhat unpredictable timing - which may be important, for example, if you're trying to decide whether to load non-targeted vs targeted ads. (which you could still do with a Promise-based API, e.g. using `Promise.race()` - but it may be less obvious, and we're already seeing both vendors and clients implementing a lot of buggy code with the v1.1 API.)

**Comment by wittjill** [comment]
Appreciate the thoughts and apologies for late response. This was deemed too much of a change during the public comment period, so we've kept the prior approach.
