### ISSUE TITLE
Publish the CMP Validator

### ISSUE THREAD

**Issue by mindplay-dk** [InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework#98]
According to the [CMP Validator User Guide](https://cmp-validator.consensu.org/chrome-extension/latest/IAB-Europe-CMP-Validator-User-Guide.pdf):

> The Validator has been published to the Chrome Web Store in private mode. This means it
does not appear in searches and is only available to authorised users.
>
> Only CMPs registered with the Transparency & Consent Framework (TCF), or publishers
running an IAB TCF registered CMP, are authorised to use the tool.

I find this really problematic.

I have spent considerable time explaining to an (expensive, certified) CMP vendor how their implementation is broken and violates the specification. This is extremely frustrating and a huge waste of time - for me, and for the CMP vendor, who has to read through lengthy e-mails with screenshots and complex explanations, quotes from the specification, and so on.

If there's a tool that would simply test and report problems with any given CMP, that would be hugely helpful in situations like this.

Keeping this tool under lock is also hugely harmful to open-source adoption of the TCF - I know of at least one open-source CMP that breaks the spec, and the situation is pretty much the same here: long descriptions, screenshots, quoting the spec; huge waste of time.

It's also really problematic that certified CMP vendors, with thousands of deployments, get away with this - think of the number of clients who risk being legally and financially liable for any defects or shortcomings of a CMP under the GDRP and ePrivacy Regulations.

Presumably, you use this secret tool as part of your certification process? This is also problematic. Since there are certified CMP vendors currently shipping defective products, this tells me your cerfication is a one-time process? If so, a one-time certification, naturally, does not guarantee that a given CMP is still compliant and functional at any later time, as they continue to develop their product.

Do you monitor certified CMPs for ongoing compliance? If so, this points to an uncovered area. 

If this were open source, we, the community, could help.

If the tool were at least available to the public, clients would at least be able to regularly verify their CMP vendor for compliance - something a corporate policy or legal departiment would very likely stipulate, since a defective CMP is potentially a legal and financial liability.

You don't specify why this tool is kept from the public, which leaves us to speculate - and I'm not going to state my own suspicions here, but lets just say, this isn't the sort of approach that inspires trust or confidence, in you, or in a CMP vendor.

Please reconsider.

**Comment by wittjill** [comment]
the validator is managed by IAB Europe; please send validator feedback to  tcf.compliance@iabeurope.eu
